<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PHRORequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    // public function messages()
    // {
    //     return [
    //         'required' => 'Field ini harus diisi minimal dengan angka 0',
    //         'numeric' => 'Field ini harus dalam format numeric'
    //     ];
    // }

    public function rules()
    {
        return [
            'pelanggaran_lalu_lintas_tilang_p' => 'required|numeric',
            'pelanggaran_lalu_lintas_teguran_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_gun_helm_sni_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_melawan_arus_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_gun_hp_saat_berkendara_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_berkendara_dibawah_pengaruh_alkohol_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_melebihi_batas_kecepatan_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_berkendara_dibawah_umur_p' => 'required|numeric',
            'pelanggaran_sepeda_motor_lain_lain_p' => 'required|numeric',
            'pelanggaran_mobil_melawan_arus_p' => 'required|numeric',
            'pelanggaran_mobil_gun_hp_saat_berkendara_p' => 'required|numeric',
            'pelanggaran_mobil_berkendara_dibawah_pengaruh_alkohol_p' => 'required|numeric',
            'pelanggaran_mobil_melebihi_batas_kecepatan_p' => 'required|numeric',
            'pelanggaran_mobil_berkendara_dibawah_umur_p' => 'required|numeric',
            'pelanggaran_mobil_gun_safety_belt_p' => 'required|numeric',
            'pelanggaran_mobil_lain_lain_p' => 'required|numeric',
            'barang_bukti_yg_disita_sim_p' => 'required|numeric',
            'barang_bukti_yg_disita_stnk_p' => 'required|numeric',
            'barang_bukti_yg_disita_kendaraan_p' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_sepeda_motor_p' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_penumpang_p' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_bus_p' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_barang_p' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_kendaraan_khusus_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pns_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_karyawan_swasta_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pelajar_mahasiswa_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pengemudi_supir_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_tni_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_polri_p' => 'required|numeric',
            'profesi_pelaku_pelanggaran_lain_lain_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_kurang_dari_15_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_16_20_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_21_25_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_26_30_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_31_35_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_36_40_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_41_45_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_46_50_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_51_55_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_56_60_tahun_p' => 'required|numeric',
            'usia_pelaku_pelanggaran_diatas_60_tahun_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_a_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_a_umum_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b1_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b1_umum_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b2_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b2_umum_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_c_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_d_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_internasional_p' => 'required|numeric',
            'sim_pelaku_pelanggaran_tanpa_sim_p' => 'required|numeric',
            'lokasi_pelanggaran_pemukiman_p' => 'required|numeric',
            'lokasi_pelanggaran_perbelanjaan_p' => 'required|numeric',
            'lokasi_pelanggaran_perkantoran_p' => 'required|numeric',
            'lokasi_pelanggaran_wisata_p' => 'required|numeric',
            'lokasi_pelanggaran_industri_p' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_nasional_p' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_propinsi_p' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_kab_kota_p' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_desa_lingkungan_p' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_arteri_p' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_kolektor_p' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_lokal_p' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_lingkungan_p' => 'required|numeric',
            'kecelakaan_lalin_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_jumlah_kerugian_materiil_p' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_sim_p' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_stnk_p' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_kendaraan_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pns_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_karwayan_swasta_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pelajar_mahasiswa_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pengemudi_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_tni_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_polri_p' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_lain_lain_p' => 'required|numeric',
            'usia_korban_kecelakaan_kurang_15_p' => 'required|numeric',
            'usia_korban_kecelakaan_16_20_p' => 'required|numeric',
            'usia_korban_kecelakaan_21_25_p' => 'required|numeric',
            'usia_korban_kecelakaan_26_30_p' => 'required|numeric',
            'usia_korban_kecelakaan_31_35_p' => 'required|numeric',
            'usia_korban_kecelakaan_36_40_p' => 'required|numeric',
            'usia_korban_kecelakaan_41_45_p' => 'required|numeric',
            'usia_korban_kecelakaan_45_50_p' => 'required|numeric',
            'usia_korban_kecelakaan_51_55_p' => 'required|numeric',
            'usia_korban_kecelakaan_56_60_p' => 'required|numeric',
            'usia_korban_kecelakaan_diatas_60_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_a_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_a_umum_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b1_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b1_umum_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b2_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b2_umum_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_c_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_d_p' => 'required|numeric',
            'sim_korban_kecelakaan_sim_internasional_p' => 'required|numeric',
            'sim_korban_kecelakaan_tanpa_sim_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_sepeda_motor_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_penumpang_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_bus_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_barang_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_kendaraan_khusus_p' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_kendaraan_tidak_bermotor_p' => 'required|numeric',
            'jenis_kecelakaan_tunggal_ooc_p' => 'required|numeric',
            'jenis_kecelakaan_depan_depan_p' => 'required|numeric',
            'jenis_kecelakaan_depan_belakang_p' => 'required|numeric',
            'jenis_kecelakaan_depan_samping_p' => 'required|numeric',
            'jenis_kecelakaan_beruntun_p' => 'required|numeric',
            'jenis_kecelakaan_pejalan_kaki_p' => 'required|numeric',
            'jenis_kecelakaan_tabrak_lari_p' => 'required|numeric',
            'jenis_kecelakaan_tabrak_hewan_p' => 'required|numeric',
            'jenis_kecelakaan_samping_samping_p' => 'required|numeric',
            'jenis_kecelakaan_lainnya_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_pns_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_karyawan_swasta_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_mahasiswa_pelajar_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_pengemudi_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_tni_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_polri_p' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_lain_lain_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_kurang_dari_15_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_16_20_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_21_25_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_26_30_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_31_35_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_36_40_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_41_45_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_46_50_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_51_55_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_56_60_tahun_p' => 'required|numeric',
            'usia_pelaku_kecelakaan_diatas_60_tahun_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_a_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_a_umum_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b1_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b1_umum_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b2_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b2_umum_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_c_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_d_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_internasional_p' => 'required|numeric',
            'sim_pelaku_kecelakaan_tanpa_sim_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_pemukiman_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_perbelanjaan_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_perkantoran_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_wisata_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_industri_p' => 'required|numeric',
            'lokasi_kecelakaan_lalin_lain_lain_p' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_nasional_p' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_propinsi_p' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_kab_kota_p' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_desa_lingkungan_p' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_arteri_p' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_kolektor_p' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_lokal_p' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_lingkungan_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_ngantuk_lelah_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_mabuk_obat_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_sakit_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_handphone_elektronik_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_menerobos_lampu_merah_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_melanggar_batas_kecepatan_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_menjaga_jarak_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_mendahului_berbelok_pindah_jalur_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_berpindah_jalur_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_memberikan_lampu_isyarat_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_mengutamakan_pejalan_kaki_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_lainnya_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_alam_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_kelaikan_kendaraan_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_kondisi_jalan_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_rambu_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_marka_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_apil_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_perlintasan_ka_palang_pintu_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_00_03_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_03_06_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_06_09_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_09_12_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_12_15_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_15_18_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_18_21_p' => 'required|numeric',
            'waktu_kejadian_kecelakaan_21_24_p' => 'required|numeric',
            'kecelakaan_lalin_menonjol_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_menonjol_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tunggal_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tunggal_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_roda_empat_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_roda_empat_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_roda_empat_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_roda_empat_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_roda_empat_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_tidak_bermotor_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_tidak_bermotor_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_tabrak_tidak_bermotor_materiil_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_jumlah_kejadian_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_berpalang_pintu_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_tidak_berpalang_pintu_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_luka_ringan_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_luka_berat_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_meninggal_p' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_materiil_p' => 'required|numeric',
            'kecelakaan_transportasi_kereta_api_p' => 'required|numeric',
            'kecelakaan_transportasi_laut_perairan_p' => 'required|numeric',
            'kecelakaan_transportasi_udara_p' => 'required|numeric',
            'penlu_melalui_media_cetak_p' => 'required|numeric',
            'penlu_melalui_media_elektronik_p' => 'required|numeric',
            'penlu_melalui_tempat_keramaian_p' => 'required|numeric',
            'penlu_melalui_tempat_istirahat_p' => 'required|numeric',
            'penlu_melalui_daerah_rawan_laka_dan_langgar_p' => 'required|numeric',
            'penyebaran_pemasangan_spanduk_p' => 'required|numeric',
            'penyebaran_pemasangan_leaflet_p' => 'required|numeric',
            'penyebaran_pemasangan_sticker_p' => 'required|numeric',
            'penyebaran_pemasangan_bilboard_p' => 'required|numeric',
            'polisi_sahabat_anak_p' => 'required|numeric',
            'cara_aman_sekolah_p' => 'required|numeric',
            'patroli_keamanan_sekolah_p' => 'required|numeric',
            'pramuka_bhayangkara_krida_lalu_lintas_p' => 'required|numeric',
            'police_goes_to_campus_p' => 'required|numeric',
            'safety_riding_driving_p' => 'required|numeric',
            'forum_lalu_lintas_angkutan_umum_p' => 'required|numeric',
            'kampanye_keselamatan_p' => 'required|numeric',
            'sekolah_mengemudi_p' => 'required|numeric',
            'taman_lalu_lintas_p' => 'required|numeric',
            'global_road_safety_partnership_action_p' => 'required|numeric',
            'giat_lantas_pengaturan_p' => 'required|numeric',
            'giat_lantas_penjagaan_p' => 'required|numeric',
            'giat_lantas_pengawalan_p' => 'required|numeric',
            'giat_lantas_patroli_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_manusia_p' => 'required|numeric',
            'faktor_penyebab_kecelakaan_prasarana_jalan_p' => 'required|numeric',
        ];
    }
}
