<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PHRORequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function messages()
    {
        return [
            'required' => 'Field ini harus diisi minimal dengan angka 0',
            'numeric' => 'Field ini harus dalam format numeric'
        ];
    }

    public function rules()
    {
        return [
            'pelanggaran_lalu_lintas_tilang' => 'required|numeric',
            'pelanggaran_lalu_lintas_teguran' => 'required|numeric',
            'pelanggaran_sepeda_motor_gun_helm_sni' => 'required|numeric',
            'pelanggaran_sepeda_motor_melawan_arus' => 'required|numeric',
            'pelanggaran_sepeda_motor_gun_hp_saat_berkendara' => 'required|numeric',
            'pelanggaran_sepeda_motor_berkendara_dibawah_pengaruh_alkohol' => 'required|numeric',
            'pelanggaran_sepeda_motor_melebihi_batas_kecepatan' => 'required|numeric',
            'pelanggaran_sepeda_motor_berkendara_dibawah_umur' => 'required|numeric',
            'pelanggaran_sepeda_motor_lain_lain' => 'required|numeric',
            'pelanggaran_mobil_melawan_arus' => 'required|numeric',
            'pelanggaran_mobil_gun_hp_saat_berkendara' => 'required|numeric',
            'pelanggaran_mobil_berkendara_dibawah_pengaruh_alkohol' => 'required|numeric',
            'pelanggaran_mobil_melebihi_batas_kecepatan' => 'required|numeric',
            'pelanggaran_mobil_berkendara_dibawah_umur' => 'required|numeric',
            'pelanggaran_mobil_gun_safety_belt' => 'required|numeric',
            'pelanggaran_mobil_lain_lain' => 'required|numeric',
            'barang_bukti_yg_disita_sim' => 'required|numeric',
            'barang_bukti_yg_disita_stnk' => 'required|numeric',
            'barang_bukti_yg_disita_kendaraan' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_sepeda_motor' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_penumpang' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_bus' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_mobil_barang' => 'required|numeric',
            'kendaraan_yang_terlibat_pelanggaran_kendaraan_khusus' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pns' => 'required|numeric',
            'profesi_pelaku_pelanggaran_karyawan_swasta' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pelajar_mahasiswa' => 'required|numeric',
            'profesi_pelaku_pelanggaran_pengemudi_supir' => 'required|numeric',
            'profesi_pelaku_pelanggaran_tni' => 'required|numeric',
            'profesi_pelaku_pelanggaran_polri' => 'required|numeric',
            'profesi_pelaku_pelanggaran_lain_lain' => 'required|numeric',
            'usia_pelaku_pelanggaran_kurang_dari_15_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_16_20_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_21_25_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_26_30_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_31_35_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_36_40_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_41_45_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_46_50_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_51_55_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_56_60_tahun' => 'required|numeric',
            'usia_pelaku_pelanggaran_diatas_60_tahun' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_a' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_a_umum' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b1' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b1_umum' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b2' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_b2_umum' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_c' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_d' => 'required|numeric',
            'sim_pelaku_pelanggaran_sim_internasional' => 'required|numeric',
            'sim_pelaku_pelanggaran_tanpa_sim' => 'required|numeric',
            'lokasi_pelanggaran_pemukiman' => 'required|numeric',
            'lokasi_pelanggaran_perbelanjaan' => 'required|numeric',
            'lokasi_pelanggaran_perkantoran' => 'required|numeric',
            'lokasi_pelanggaran_wisata' => 'required|numeric',
            'lokasi_pelanggaran_industri' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_nasional' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_propinsi' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_kab_kota' => 'required|numeric',
            'lokasi_pelanggaran_status_jalan_desa_lingkungan' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_arteri' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_kolektor' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_lokal' => 'required|numeric',
            'lokasi_pelanggaran_fungsi_jalan_lingkungan' => 'required|numeric',
            'kecelakaan_lalin_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_jumlah_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_jumlah_kerugian_materiil' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_sim' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_stnk' => 'required|numeric',
            'kecelakaan_barang_bukti_yg_disita_kendaraan' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pns' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_karwayan_swasta' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pelajar_mahasiswa' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_pengemudi' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_tni' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_polri' => 'required|numeric',
            'profesi_korban_kecelakaan_lalin_lain_lain' => 'required|numeric',
            'usia_korban_kecelakaan_kurang_15' => 'required|numeric',
            'usia_korban_kecelakaan_16_20' => 'required|numeric',
            'usia_korban_kecelakaan_21_25' => 'required|numeric',
            'usia_korban_kecelakaan_26_30' => 'required|numeric',
            'usia_korban_kecelakaan_31_35' => 'required|numeric',
            'usia_korban_kecelakaan_36_40' => 'required|numeric',
            'usia_korban_kecelakaan_41_45' => 'required|numeric',
            'usia_korban_kecelakaan_45_50' => 'required|numeric',
            'usia_korban_kecelakaan_51_55' => 'required|numeric',
            'usia_korban_kecelakaan_56_60' => 'required|numeric',
            'usia_korban_kecelakaan_diatas_60' => 'required|numeric',
            'sim_korban_kecelakaan_sim_a' => 'required|numeric',
            'sim_korban_kecelakaan_sim_a_umum' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b1' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b1_umum' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b2' => 'required|numeric',
            'sim_korban_kecelakaan_sim_b2_umum' => 'required|numeric',
            'sim_korban_kecelakaan_sim_c' => 'required|numeric',
            'sim_korban_kecelakaan_sim_d' => 'required|numeric',
            'sim_korban_kecelakaan_sim_internasional' => 'required|numeric',
            'sim_korban_kecelakaan_tanpa_sim' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_sepeda_motor' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_penumpang' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_bus' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_mobil_barang' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_kendaraan_khusus' => 'required|numeric',
            'kendaraan_yg_terlibat_kecelakaan_kendaraan_tidak_bermotor' => 'required|numeric',
            'jenis_kecelakaan_tunggal_ooc' => 'required|numeric',
            'jenis_kecelakaan_depan_depan' => 'required|numeric',
            'jenis_kecelakaan_depan_belakang' => 'required|numeric',
            'jenis_kecelakaan_depan_samping' => 'required|numeric',
            'jenis_kecelakaan_beruntun' => 'required|numeric',
            'jenis_kecelakaan_pejalan_kaki' => 'required|numeric',
            'jenis_kecelakaan_tabrak_lari' => 'required|numeric',
            'jenis_kecelakaan_tabrak_hewan' => 'required|numeric',
            'jenis_kecelakaan_samping_samping' => 'required|numeric',
            'jenis_kecelakaan_lainnya' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_pns' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_karyawan_swasta' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_mahasiswa_pelajar' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_pengemudi' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_tni' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_polri' => 'required|numeric',
            'profesi_pelaku_kecelakaan_lalin_lain_lain' => 'required|numeric',
            'usia_pelaku_kecelakaan_kurang_dari_15_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_16_20_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_21_25_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_26_30_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_31_35_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_36_40_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_41_45_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_46_50_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_51_55_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_56_60_tahun' => 'required|numeric',
            'usia_pelaku_kecelakaan_diatas_60_tahun' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_a' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_a_umum' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b1' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b1_umum' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b2' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_b2_umum' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_c' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_d' => 'required|numeric',
            'sim_pelaku_kecelakaan_sim_internasional' => 'required|numeric',
            'sim_pelaku_kecelakaan_tanpa_sim' => 'required|numeric',
            'lokasi_kecelakaan_lalin_pemukiman' => 'required|numeric',
            'lokasi_kecelakaan_lalin_perbelanjaan' => 'required|numeric',
            'lokasi_kecelakaan_lalin_perkantoran' => 'required|numeric',
            'lokasi_kecelakaan_lalin_wisata' => 'required|numeric',
            'lokasi_kecelakaan_lalin_industri' => 'required|numeric',
            'lokasi_kecelakaan_lalin_lain_lain' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_nasional' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_propinsi' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_kab_kota' => 'required|numeric',
            'lokasi_kecelakaan_status_jalan_desa_lingkungan' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_arteri' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_kolektor' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_lokal' => 'required|numeric',
            'lokasi_kecelakaan_fungsi_jalan_lingkungan' => 'required|numeric',
            'faktor_penyebab_kecelakaan_ngantuk_lelah' => 'required|numeric',
            'faktor_penyebab_kecelakaan_mabuk_obat' => 'required|numeric',
            'faktor_penyebab_kecelakaan_sakit' => 'required|numeric',
            'faktor_penyebab_kecelakaan_hanphone_eletronik' => 'required|numeric',
            'faktor_penyebab_kecelakaan_menerobos_lampu_merah' => 'required|numeric',
            'faktor_penyebab_kecelakaan_melanggar_batas_kecepatan' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_menjaga_jarak' => 'required|numeric',
            'faktor_penyebab_kecelakaan_mendahului_berbelok_pindah_jalur' => 'required|numeric',
            'faktor_penyebab_kecelakaan_berpindah_jalur' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_memberikan_lampu_isyarat' => 'required|numeric',
            'faktor_penyebab_kecelakaan_tidak_mengutamakan_pejalan_kaki' => 'required|numeric',
            'faktor_penyebab_kecelakaan_lainnya' => 'required|numeric',
            'faktor_penyebab_kecelakaan_alam' => 'required|numeric',
            'faktor_penyebab_kecelakaan_kelaikan_kendaraan' => 'required|numeric',
            'faktor_penyebab_kecelakaan_kondisi_jalan' => 'required|numeric',
            'faktor_penyebab_kecelakaan_rambu' => 'required|numeric',
            'faktor_penyebab_kecelakaan_marka' => 'required|numeric',
            'faktor_penyebab_kecelakaan_apil' => 'required|numeric',
            'faktor_penyebab_kecelakaan_perlintasan_ka_palang_pintu' => 'required|numeric',
            'waktu_kejadian_kecelakaan_00_03' => 'required|numeric',
            'waktu_kejadian_kecelakaan_03_06' => 'required|numeric',
            'waktu_kejadian_kecelakaan_06_09' => 'required|numeric',
            'waktu_kejadian_kecelakaan_09_12' => 'required|numeric',
            'waktu_kejadian_kecelakaan_12_15' => 'required|numeric',
            'waktu_kejadian_kecelakaan_15_18' => 'required|numeric',
            'waktu_kejadian_kecelakaan_18_21' => 'required|numeric',
            'waktu_kejadian_kecelakaan_21_24' => 'required|numeric',
            'kecelakaan_lalin_menonjol_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_menonjol_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_menonjol_materiil' => 'required|numeric',
            'kecelakaan_lalin_tunggal_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tunggal_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tunggal_materiil' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tabrak_pejalan_kaki_materiil' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tabrak_lari_materiil' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tabrak_sepeda_motor_materiil' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_bermotor_roda_empat_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_bermotor_roda_empat_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_bermotor_roda_empat_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_bermotor_roda_empat_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_bermotor_roda_empat_materiil' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_tidak_bermotor_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_tidak_bermotor_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_tidak_bermotor_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_tidak_bermotor_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_tabrak_kendaraan_tidak_bermotor_materiil' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_jumlah_kejadian' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_berpalang_pintu' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_tidak_berpalang_pintu' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_luka_ringan' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_luka_berat' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_korban_meninggal' => 'required|numeric',
            'kecelakaan_lalin_perlintasan_ka_materiil' => 'required|numeric',
            'kecelakaan_transportasi_kereta_api' => 'required|numeric',
            'kecelakaan_transportasi_laut_perairan' => 'required|numeric',
            'kecelakaan_transportasi_udara' => 'required|numeric',
            'penlu_melalui_media_cetak' => 'required|numeric',
            'penlu_melalui_media_elektronik' => 'required|numeric',
            'penlu_melalui_tempat_keramaian' => 'required|numeric',
            'penlu_melalui_tempat_istirahat' => 'required|numeric',
            'penlu_melalui_daerah_rawan_laka_dan_langgar' => 'required|numeric',
            'penyebaran_pemasangan_spanduk' => 'required|numeric',
            'penyebaran_pemasangan_leaflet' => 'required|numeric',
            'penyebaran_pemasangan_sticker' => 'required|numeric',
            'penyebaran_pemasangan_bilboard' => 'required|numeric',
            'polisi_sahabat_anak' => 'required|numeric',
            'cara_aman_sekolah' => 'required|numeric',
            'patroli_keamanan_sekolah' => 'required|numeric',
            'pramuka_bhayangkara_krida_lalu_lintas' => 'required|numeric',
            'police_goes_to_campus' => 'required|numeric',
            'safety_riding_driving' => 'required|numeric',
            'forum_lalu_lintas_angkutan_umum' => 'required|numeric',
            'kampanye_keselamatan' => 'required|numeric',
            'sekolah_mengemudi' => 'required|numeric',
            'taman_lalu_lintas' => 'required|numeric',
            'global_road_safety_partnership_action' => 'required|numeric',
            'giat_lantas_pengaturan' => 'required|numeric',
            'giat_lantas_penjagaan' => 'required|numeric',
            'giat_lantas_pengawalan' => 'required|numeric',
            'giat_lantas_patroli' => 'required|numeric',
        ];
    }
}
