<?php

use App\Models\SortablePoldaReport;
use PhpOffice\PhpSpreadsheet\IOFactory;
use Illuminate\Database\Eloquent\Builder;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (! function_exists('lapoanPerpoldaPerhari')) {
    function lapoanPerpoldaPerhari($data, $rencanaOperasi, $startDate, $endDate, $dailyRekap=null) {
        $arraylabel = [
            'C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL'
        ];

        $now = now()->format("Y-m-d");

        $filename = "LAPORAN-PERPOLPA-PERHARI";

        $excelPath = public_path('template/excel');
        $excelTemplate = $excelPath."/laporan_perpolda_perhari.xlsx";
        $spreadsheet = IOFactory::load($excelTemplate);

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$filename.'.xlsx"');

        $sheet = $spreadsheet->getActiveSheet();

        $sheet->setCellValue('A5', 'REKAPITULASI LAPORAN PERPOLDA '.gedein($rencanaOperasi->name).' '.date('Y'));
        $sheet->setCellValue('A6', 'TANGGAL '.strtoupper(indonesiaDate($startDate)).' s.d. '.strtoupper(indonesiaDate($endDate)));

        foreach($data as $key=>$value) {
            $poldaName  = $value->polda_name;
            $poldaId    = $value->polda_id;

            $sheet->setCellValue($arraylabel[$key].'12', applyZero($value->current_pelanggaran_lalu_lintas_tilang_sum));
            $sheet->setCellValue($arraylabel[$key].'13', applyZero($value->current_pelanggaran_lalu_lintas_teguran_sum));
            $sheet->setCellValue($arraylabel[$key].'13', applyZero($value->current_pelanggaran_lalu_lintas_teguran_sum));
            $sheet->setCellValue($arraylabel[$key].'17', applyZero($value->current_pelanggaran_sepeda_motor_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'18', applyZero($value->current_pelanggaran_sepeda_motor_helm_sum));
            $sheet->setCellValue($arraylabel[$key].'19', applyZero($value->current_pelanggaran_sepeda_motor_bonceng_lebih_dari_satu_sum));
            $sheet->setCellValue($arraylabel[$key].'20', applyZero($value->current_pelanggaran_sepeda_motor_marka_menerus_menyalip_sum));
            $sheet->setCellValue($arraylabel[$key].'21', applyZero($value->current_pelanggaran_sepeda_motor_melawan_arus_sum));
            $sheet->setCellValue($arraylabel[$key].'22', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_lampu_lalin_sum));
            $sheet->setCellValue($arraylabel[$key].'23', applyZero($value->current_pelanggaran_sepeda_motor_mengemudikan_tidak_wajar_sum));
            $sheet->setCellValue($arraylabel[$key].'24', applyZero($value->current_pelanggaran_sepeda_motor_syarat_teknis_layak_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'25', applyZero($value->current_pelanggaran_sepeda_motor_tidak_nyala_lampu_siang_malam_sum));
            $sheet->setCellValue($arraylabel[$key].'26', applyZero($value->current_pelanggaran_sepeda_motor_berbelok_tanpa_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'27', applyZero($value->current_pelanggaran_sepeda_motor_berbalapan_di_jalan_raya_sum));
            $sheet->setCellValue($arraylabel[$key].'28', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_rambu_berhenti_dan_parkir_sum));
            $sheet->setCellValue($arraylabel[$key].'29', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_marka_berhenti_sum));
            $sheet->setCellValue($arraylabel[$key].'30', applyZero($value->current_pelanggaran_sepeda_motor_tidak_patuh_perintah_petugas_sum));
            $sheet->setCellValue($arraylabel[$key].'31', applyZero($value->current_pelanggaran_sepeda_motor_surat_surat_sum));
            $sheet->setCellValue($arraylabel[$key].'32', applyZero($value->current_pelanggaran_sepeda_motor_kelengkapan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'33', applyZero($value->current_pelanggaran_sepeda_motor_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'36', applyZero($value->current_pelanggaran_mobil_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'37', applyZero($value->current_pelanggaran_mobil_safety_belt_sum));
            $sheet->setCellValue($arraylabel[$key].'38', applyZero($value->current_pelanggaran_mobil_muatan_overload_sum));
            $sheet->setCellValue($arraylabel[$key].'39', applyZero($value->current_pelanggaran_mobil_marka_menerus_menyalip_sum));
            $sheet->setCellValue($arraylabel[$key].'40', applyZero($value->current_pelanggaran_mobil_melawan_arus_sum));
            $sheet->setCellValue($arraylabel[$key].'41', applyZero($value->current_pelanggaran_mobil_melanggar_lampu_lalin_sum));
            $sheet->setCellValue($arraylabel[$key].'42', applyZero($value->current_pelanggaran_mobil_mengemudi_tidak_wajar_sum));
            $sheet->setCellValue($arraylabel[$key].'43', applyZero($value->current_pelanggaran_mobil_syarat_teknis_layak_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'44', applyZero($value->current_pelanggaran_mobil_tidak_nyala_lampu_malam_sum));
            $sheet->setCellValue($arraylabel[$key].'45', applyZero($value->current_pelanggaran_mobil_berbelok_tanpa_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'46', applyZero($value->current_pelanggaran_mobil_berbalapan_di_jalan_raya_sum));
            $sheet->setCellValue($arraylabel[$key].'47', applyZero($value->current_pelanggaran_mobil_melanggar_rambu_berhenti_dan_parkir_sum));
            $sheet->setCellValue($arraylabel[$key].'48', applyZero($value->current_pelanggaran_mobil_melanggar_marka_berhenti_sum));
            $sheet->setCellValue($arraylabel[$key].'49', applyZero($value->current_pelanggaran_mobil_tidak_patuh_perintah_petugas_sum));
            $sheet->setCellValue($arraylabel[$key].'50', applyZero($value->current_pelanggaran_mobil_surat_surat_sum));
            $sheet->setCellValue($arraylabel[$key].'51', applyZero($value->current_pelanggaran_mobil_kelengkapan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'52', applyZero($value->current_pelanggaran_mobil_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'55', applyZero($value->current_pelanggaran_pejalan_kaki_menyeberang_tidak_pada_tempat_sum));
            $sheet->setCellValue($arraylabel[$key].'58', applyZero($value->current_barang_bukti_yg_disita_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'59', applyZero($value->current_barang_bukti_yg_disita_stnk_sum));
            $sheet->setCellValue($arraylabel[$key].'60', applyZero($value->current_barang_bukti_yg_disita_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'63', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_sepeda_motor_sum));
            $sheet->setCellValue($arraylabel[$key].'64', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_penumpang_sum));
            $sheet->setCellValue($arraylabel[$key].'65', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_bus_sum));
            $sheet->setCellValue($arraylabel[$key].'66', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_barang_sum));
            $sheet->setCellValue($arraylabel[$key].'67', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_kendaraan_khusus_sum));
            $sheet->setCellValue($arraylabel[$key].'70', applyZero($value->current_profesi_pelaku_pelanggaran_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'71', applyZero($value->current_profesi_pelaku_pelanggaran_karyawan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'72', applyZero($value->current_profesi_pelaku_pelanggaran_pelajar_mahasiswa_sum));
            $sheet->setCellValue($arraylabel[$key].'73', applyZero($value->current_profesi_pelaku_pelanggaran_pengemudi_supir_sum));
            $sheet->setCellValue($arraylabel[$key].'74', applyZero($value->current_profesi_pelaku_pelanggaran_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'75', applyZero($value->current_profesi_pelaku_pelanggaran_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'76', applyZero($value->current_profesi_pelaku_pelanggaran_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'79', applyZero($value->current_usia_pelaku_pelanggaran_kurang_dari_15_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'80', applyZero($value->current_usia_pelaku_pelanggaran_16_20_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'81', applyZero($value->current_usia_pelaku_pelanggaran_21_25_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'82', applyZero($value->current_usia_pelaku_pelanggaran_26_30_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'83', applyZero($value->current_usia_pelaku_pelanggaran_31_35_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'84', applyZero($value->current_usia_pelaku_pelanggaran_36_40_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'85', applyZero($value->current_usia_pelaku_pelanggaran_41_45_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'86', applyZero($value->current_usia_pelaku_pelanggaran_46_50_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'87', applyZero($value->current_usia_pelaku_pelanggaran_51_55_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'88', applyZero($value->current_usia_pelaku_pelanggaran_56_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'89', applyZero($value->current_usia_pelaku_pelanggaran_diatas_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'92', applyZero($value->current_sim_pelaku_pelanggaran_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'93', applyZero($value->current_sim_pelaku_pelanggaran_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'94', applyZero($value->current_sim_pelaku_pelanggaran_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'95', applyZero($value->current_sim_pelaku_pelanggaran_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'96', applyZero($value->current_sim_pelaku_pelanggaran_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'97', applyZero($value->current_sim_pelaku_pelanggaran_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'98', applyZero($value->current_sim_pelaku_pelanggaran_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'99', applyZero($value->current_sim_pelaku_pelanggaran_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'100', applyZero($value->current_sim_pelaku_pelanggaran_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'101', applyZero($value->current_sim_pelaku_pelanggaran_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'105', applyZero($value->current_lokasi_pelanggaran_pemukiman_sum));
            $sheet->setCellValue($arraylabel[$key].'106', applyZero($value->current_lokasi_pelanggaran_perbelanjaan_sum));
            $sheet->setCellValue($arraylabel[$key].'107', applyZero($value->current_lokasi_pelanggaran_perkantoran_sum));
            $sheet->setCellValue($arraylabel[$key].'108', applyZero($value->current_lokasi_pelanggaran_wisata_sum));
            $sheet->setCellValue($arraylabel[$key].'109', applyZero($value->current_lokasi_pelanggaran_industri_sum));
            $sheet->setCellValue($arraylabel[$key].'112', applyZero($value->current_lokasi_pelanggaran_status_jalan_nasional_sum));
            $sheet->setCellValue($arraylabel[$key].'113', applyZero($value->current_lokasi_pelanggaran_status_jalan_propinsi_sum));
            $sheet->setCellValue($arraylabel[$key].'114', applyZero($value->current_lokasi_pelanggaran_status_jalan_kab_kota_sum));
            $sheet->setCellValue($arraylabel[$key].'115', applyZero($value->current_lokasi_pelanggaran_status_jalan_desa_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'118', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_arteri_sum));
            $sheet->setCellValue($arraylabel[$key].'119', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_kolektor_sum));
            $sheet->setCellValue($arraylabel[$key].'120', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_lokal_sum));
            $sheet->setCellValue($arraylabel[$key].'121', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'125', applyZero($value->current_kecelakaan_lalin_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'126', applyZero($value->current_kecelakaan_lalin_jumlah_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'127', applyZero($value->current_kecelakaan_lalin_jumlah_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'128', applyZero($value->current_kecelakaan_lalin_jumlah_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'129', applyZero($value->current_kecelakaan_lalin_jumlah_kerugian_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'131', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'132', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_stnk_sum));
            $sheet->setCellValue($arraylabel[$key].'133', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'136', applyZero($value->current_profesi_korban_kecelakaan_lalin_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'137', applyZero($value->current_profesi_korban_kecelakaan_lalin_karwayan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'138', applyZero($value->current_profesi_korban_kecelakaan_lalin_pelajar_mahasiswa_sum));
            $sheet->setCellValue($arraylabel[$key].'139', applyZero($value->current_profesi_korban_kecelakaan_lalin_pengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'140', applyZero($value->current_profesi_korban_kecelakaan_lalin_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'141', applyZero($value->current_profesi_korban_kecelakaan_lalin_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'142', applyZero($value->current_profesi_korban_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'145', applyZero($value->current_usia_korban_kecelakaan_kurang_15_sum));
            $sheet->setCellValue($arraylabel[$key].'146', applyZero($value->current_usia_korban_kecelakaan_16_20_sum));
            $sheet->setCellValue($arraylabel[$key].'147', applyZero($value->current_usia_korban_kecelakaan_21_25_sum));
            $sheet->setCellValue($arraylabel[$key].'148', applyZero($value->current_usia_korban_kecelakaan_26_30_sum));
            $sheet->setCellValue($arraylabel[$key].'149', applyZero($value->current_usia_korban_kecelakaan_31_35_sum));
            $sheet->setCellValue($arraylabel[$key].'150', applyZero($value->current_usia_korban_kecelakaan_36_40_sum));
            $sheet->setCellValue($arraylabel[$key].'151', applyZero($value->current_usia_korban_kecelakaan_41_45_sum));
            $sheet->setCellValue($arraylabel[$key].'152', applyZero($value->current_usia_korban_kecelakaan_45_50_sum));
            $sheet->setCellValue($arraylabel[$key].'153', applyZero($value->current_usia_korban_kecelakaan_51_55_sum));
            $sheet->setCellValue($arraylabel[$key].'154', applyZero($value->current_usia_korban_kecelakaan_56_60_sum));
            $sheet->setCellValue($arraylabel[$key].'155', applyZero($value->current_usia_korban_kecelakaan_diatas_60_sum));
            $sheet->setCellValue($arraylabel[$key].'158', applyZero($value->current_sim_korban_kecelakaan_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'159', applyZero($value->current_sim_korban_kecelakaan_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'160', applyZero($value->current_sim_korban_kecelakaan_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'161', applyZero($value->current_sim_korban_kecelakaan_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'162', applyZero($value->current_sim_korban_kecelakaan_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'163', applyZero($value->current_sim_korban_kecelakaan_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'164', applyZero($value->current_sim_korban_kecelakaan_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'165', applyZero($value->current_sim_korban_kecelakaan_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'166', applyZero($value->current_sim_korban_kecelakaan_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'167', applyZero($value->current_sim_korban_kecelakaan_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'170', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_sepeda_motor_sum));
            $sheet->setCellValue($arraylabel[$key].'171', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_penumpang_sum));
            $sheet->setCellValue($arraylabel[$key].'172', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_bus_sum));
            $sheet->setCellValue($arraylabel[$key].'173', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_barang_sum));
            $sheet->setCellValue($arraylabel[$key].'174', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_kendaraan_khusus_sum));
            $sheet->setCellValue($arraylabel[$key].'175', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_kendaraan_tidak_bermotor_sum));
            $sheet->setCellValue($arraylabel[$key].'178', applyZero($value->current_jenis_kecelakaan_tunggal_ooc_sum));
            $sheet->setCellValue($arraylabel[$key].'179', applyZero($value->current_jenis_kecelakaan_depan_depan_sum));
            $sheet->setCellValue($arraylabel[$key].'180', applyZero($value->current_jenis_kecelakaan_depan_belakang_sum));
            $sheet->setCellValue($arraylabel[$key].'181', applyZero($value->current_jenis_kecelakaan_depan_samping_sum));
            $sheet->setCellValue($arraylabel[$key].'182', applyZero($value->current_jenis_kecelakaan_beruntun_sum));
            $sheet->setCellValue($arraylabel[$key].'183', applyZero($value->current_jenis_kecelakaan_pejalan_kaki_sum));
            $sheet->setCellValue($arraylabel[$key].'184', applyZero($value->current_jenis_kecelakaan_tabrak_lari_sum));
            $sheet->setCellValue($arraylabel[$key].'185', applyZero($value->current_jenis_kecelakaan_tabrak_hewan_sum));
            $sheet->setCellValue($arraylabel[$key].'186', applyZero($value->current_jenis_kecelakaan_samping_samping_sum));
            $sheet->setCellValue($arraylabel[$key].'187', applyZero($value->current_jenis_kecelakaan_lainnya_sum));
            $sheet->setCellValue($arraylabel[$key].'190', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'191', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_karyawan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'192', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_mahasiswa_pelajar_sum));
            $sheet->setCellValue($arraylabel[$key].'193', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_pengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'194', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'195', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'196', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'199', applyZero($value->current_usia_pelaku_kecelakaan_kurang_dari_15_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'200', applyZero($value->current_usia_pelaku_kecelakaan_16_20_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'201', applyZero($value->current_usia_pelaku_kecelakaan_21_25_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'202', applyZero($value->current_usia_pelaku_kecelakaan_26_30_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'203', applyZero($value->current_usia_pelaku_kecelakaan_31_35_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'204', applyZero($value->current_usia_pelaku_kecelakaan_36_40_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'205', applyZero($value->current_usia_pelaku_kecelakaan_41_45_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'206', applyZero($value->current_usia_pelaku_kecelakaan_46_50_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'207', applyZero($value->current_usia_pelaku_kecelakaan_51_55_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'208', applyZero($value->current_usia_pelaku_kecelakaan_56_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'209', applyZero($value->current_usia_pelaku_kecelakaan_diatas_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'212', applyZero($value->current_sim_pelaku_kecelakaan_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'213', applyZero($value->current_sim_pelaku_kecelakaan_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'214', applyZero($value->current_sim_pelaku_kecelakaan_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'215', applyZero($value->current_sim_pelaku_kecelakaan_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'216', applyZero($value->current_sim_pelaku_kecelakaan_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'217', applyZero($value->current_sim_pelaku_kecelakaan_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'218', applyZero($value->current_sim_pelaku_kecelakaan_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'219', applyZero($value->current_sim_pelaku_kecelakaan_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'220', applyZero($value->current_sim_pelaku_kecelakaan_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'221', applyZero($value->current_sim_pelaku_kecelakaan_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'225', applyZero($value->current_lokasi_kecelakaan_lalin_pemukiman_sum));
            $sheet->setCellValue($arraylabel[$key].'226', applyZero($value->current_lokasi_kecelakaan_lalin_perbelanjaan_sum));
            $sheet->setCellValue($arraylabel[$key].'227', applyZero($value->current_lokasi_kecelakaan_lalin_perkantoran_sum));
            $sheet->setCellValue($arraylabel[$key].'228', applyZero($value->current_lokasi_kecelakaan_lalin_wisata_sum));
            $sheet->setCellValue($arraylabel[$key].'229', applyZero($value->current_lokasi_kecelakaan_lalin_industri_sum));
            $sheet->setCellValue($arraylabel[$key].'230', applyZero($value->current_lokasi_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'233', applyZero($value->current_lokasi_kecelakaan_status_jalan_nasional_sum));
            $sheet->setCellValue($arraylabel[$key].'234', applyZero($value->current_lokasi_kecelakaan_status_jalan_propinsi_sum));
            $sheet->setCellValue($arraylabel[$key].'235', applyZero($value->current_lokasi_kecelakaan_status_jalan_kab_kota_sum));
            $sheet->setCellValue($arraylabel[$key].'236', applyZero($value->current_lokasi_kecelakaan_status_jalan_desa_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'239', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_arteri_sum));
            $sheet->setCellValue($arraylabel[$key].'240', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_kolektor_sum));
            $sheet->setCellValue($arraylabel[$key].'241', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_lokal_sum));
            $sheet->setCellValue($arraylabel[$key].'242', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'245', applyZero($value->current_faktor_penyebab_kecelakaan_manusia_sum));
            $sheet->setCellValue($arraylabel[$key].'246', applyZero($value->current_faktor_penyebab_kecelakaan_ngantuk_lelah_sum));
            $sheet->setCellValue($arraylabel[$key].'247', applyZero($value->current_faktor_penyebab_kecelakaan_mabuk_obat_sum));
            $sheet->setCellValue($arraylabel[$key].'248', applyZero($value->current_faktor_penyebab_kecelakaan_sakit_sum));
            $sheet->setCellValue($arraylabel[$key].'249', applyZero($value->current_faktor_penyebab_kecelakaan_handphone_elektronik_sum));
            $sheet->setCellValue($arraylabel[$key].'250', applyZero($value->current_faktor_penyebab_kecelakaan_menerobos_lampu_merah_sum));
            $sheet->setCellValue($arraylabel[$key].'251', applyZero($value->current_faktor_penyebab_kecelakaan_melanggar_batas_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'252', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_menjaga_jarak_sum));
            $sheet->setCellValue($arraylabel[$key].'253', applyZero($value->current_faktor_penyebab_kecelakaan_mendahului_berbelok_pindah_jalur_sum));
            $sheet->setCellValue($arraylabel[$key].'254', applyZero($value->current_faktor_penyebab_kecelakaan_berpindah_jalur_sum));
            $sheet->setCellValue($arraylabel[$key].'255', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_memberikan_lampu_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'256', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_mengutamakan_pejalan_kaki_sum));
            $sheet->setCellValue($arraylabel[$key].'257', applyZero($value->current_faktor_penyebab_kecelakaan_lainnya_sum));
            $sheet->setCellValue($arraylabel[$key].'258', applyZero($value->current_faktor_penyebab_kecelakaan_alam_sum));
            $sheet->setCellValue($arraylabel[$key].'259', applyZero($value->current_faktor_penyebab_kecelakaan_kelaikan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'260', applyZero($value->current_faktor_penyebab_kecelakaan_kondisi_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'261', applyZero($value->current_faktor_penyebab_kecelakaan_prasarana_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'262', applyZero($value->current_faktor_penyebab_kecelakaan_prasarana_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'263', applyZero($value->current_faktor_penyebab_kecelakaan_marka_sum));
            $sheet->setCellValue($arraylabel[$key].'264', applyZero($value->current_faktor_penyebab_kecelakaan_apil_sum));
            $sheet->setCellValue($arraylabel[$key].'265', applyZero($value->current_faktor_penyebab_kecelakaan_perlintasan_ka_palang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'268', applyZero($value->current_waktu_kejadian_kecelakaan_00_03_sum));
            $sheet->setCellValue($arraylabel[$key].'269', applyZero($value->current_waktu_kejadian_kecelakaan_03_06_sum));
            $sheet->setCellValue($arraylabel[$key].'270', applyZero($value->current_waktu_kejadian_kecelakaan_06_09_sum));
            $sheet->setCellValue($arraylabel[$key].'271', applyZero($value->current_waktu_kejadian_kecelakaan_09_12_sum));
            $sheet->setCellValue($arraylabel[$key].'272', applyZero($value->current_waktu_kejadian_kecelakaan_12_15_sum));
            $sheet->setCellValue($arraylabel[$key].'273', applyZero($value->current_waktu_kejadian_kecelakaan_15_18_sum));
            $sheet->setCellValue($arraylabel[$key].'274', applyZero($value->current_waktu_kejadian_kecelakaan_18_21_sum));
            $sheet->setCellValue($arraylabel[$key].'275', applyZero($value->current_waktu_kejadian_kecelakaan_21_24_sum));
            $sheet->setCellValue($arraylabel[$key].'278', applyZero($value->current_kecelakaan_lalin_menonjol_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'279', applyZero($value->current_kecelakaan_lalin_menonjol_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'280', applyZero($value->current_kecelakaan_lalin_menonjol_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'281', applyZero($value->current_kecelakaan_lalin_menonjol_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'282', applyZero($value->current_kecelakaan_lalin_menonjol_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'284', applyZero($value->current_kecelakaan_lalin_tunggal_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'285', applyZero($value->current_kecelakaan_lalin_tunggal_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'286', applyZero($value->current_kecelakaan_lalin_tunggal_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'287', applyZero($value->current_kecelakaan_lalin_tunggal_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'288', applyZero($value->current_kecelakaan_lalin_tunggal_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'290', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'291', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'292', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'293', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'294', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'296', applyZero($value->current_kecelakaan_lalin_tabrak_lari_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'297', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'298', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'299', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'300', applyZero($value->current_kecelakaan_lalin_tabrak_lari_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'302', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'303', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'304', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'305', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'306', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'308', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'309', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'310', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'311', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'312', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'314', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'315', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'316', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'317', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'318', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'320', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'321', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_berpalang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'322', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_tidak_berpalang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'323', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'324', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'325', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'326', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'328', applyZero($value->current_kecelakaan_transportasi_kereta_api_sum));
            $sheet->setCellValue($arraylabel[$key].'329', applyZero($value->current_kecelakaan_transportasi_laut_perairan_sum));
            $sheet->setCellValue($arraylabel[$key].'330', applyZero($value->current_kecelakaan_transportasi_udara_sum));
            $sheet->setCellValue($arraylabel[$key].'335', applyZero($value->current_penlu_melalui_media_cetak_sum));
            $sheet->setCellValue($arraylabel[$key].'336', applyZero($value->current_penlu_melalui_media_elektronik_sum));
            $sheet->setCellValue($arraylabel[$key].'337', applyZero($value->current_penlu_melalui_media_sosial_sum));
            $sheet->setCellValue($arraylabel[$key].'338', applyZero($value->current_penlu_melalui_tempat_keramaian_sum));
            $sheet->setCellValue($arraylabel[$key].'339', applyZero($value->current_penlu_melalui_tempat_istirahat_sum));
            $sheet->setCellValue($arraylabel[$key].'340', applyZero($value->current_penlu_melalui_daerah_rawan_laka_dan_langgar_sum));
            $sheet->setCellValue($arraylabel[$key].'343', applyZero($value->current_penyebaran_pemasangan_spanduk_sum));
            $sheet->setCellValue($arraylabel[$key].'344', applyZero($value->current_penyebaran_pemasangan_leaflet_sum));
            $sheet->setCellValue($arraylabel[$key].'345', applyZero($value->current_penyebaran_pemasangan_sticker_sum));
            $sheet->setCellValue($arraylabel[$key].'346', applyZero($value->current_penyebaran_pemasangan_bilboard_sum));
            $sheet->setCellValue($arraylabel[$key].'349', applyZero($value->current_polisi_sahabat_anak_sum));
            $sheet->setCellValue($arraylabel[$key].'350', applyZero($value->current_cara_aman_sekolah_sum));
            $sheet->setCellValue($arraylabel[$key].'351', applyZero($value->current_patroli_keamanan_sekolah_sum));
            $sheet->setCellValue($arraylabel[$key].'352', applyZero($value->current_pramuka_bhayangkara_krida_lalu_lintas_sum));
            $sheet->setCellValue($arraylabel[$key].'355', applyZero($value->current_police_goes_to_campus_sum));
            $sheet->setCellValue($arraylabel[$key].'356', applyZero($value->current_safety_riding_driving_sum));
            $sheet->setCellValue($arraylabel[$key].'357', applyZero($value->current_forum_lalu_lintas_angkutan_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'358', applyZero($value->current_kampanye_keselamatan_sum));
            $sheet->setCellValue($arraylabel[$key].'359', applyZero($value->current_sekolah_mengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'360', applyZero($value->current_taman_lalu_lintas_sum));
            $sheet->setCellValue($arraylabel[$key].'361', applyZero($value->current_global_road_safety_partnership_action_sum));
            $sheet->setCellValue($arraylabel[$key].'365', applyZero($value->current_giat_lantas_pengaturan_sum));
            $sheet->setCellValue($arraylabel[$key].'366', applyZero($value->current_giat_lantas_penjagaan_sum));
            $sheet->setCellValue($arraylabel[$key].'367', applyZero($value->current_giat_lantas_pengawalan_sum));
            $sheet->setCellValue($arraylabel[$key].'368', applyZero($value->current_giat_lantas_patroli_sum));
            $sheet->setCellValue($arraylabel[$key].'373', applyZero($value->current_arus_mudik_jumlah_bus_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'374', applyZero($value->current_arus_mudik_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'375', applyZero($value->current_arus_mudik_jumlah_bus_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'376', applyZero($value->current_arus_mudik_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'377', applyZero($value->current_arus_mudik_total_terminal_sum));
            $sheet->setCellValue($arraylabel[$key].'378', applyZero($value->current_arus_mudik_total_bus_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'379', applyZero($value->current_arus_mudik_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'380', applyZero($value->current_arus_mudik_total_bus_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'381', applyZero($value->current_arus_mudik_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'383', applyZero($value->current_arus_mudik_kereta_api_total_stasiun_sum));
            $sheet->setCellValue($arraylabel[$key].'384', applyZero($value->current_arus_mudik_kereta_api_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'385', applyZero($value->current_arus_mudik_kereta_api_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'387', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'388', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r4_sum));
            $sheet->setCellValue($arraylabel[$key].'389', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r2_sum));
            $sheet->setCellValue($arraylabel[$key].'390', applyZero($value->current_arus_mudik_pelabuhan_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'391', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'392', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r4_sum));
            $sheet->setCellValue($arraylabel[$key].'393', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r2_sum));
            $sheet->setCellValue($arraylabel[$key].'394', applyZero($value->current_arus_mudik_pelabuhan_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'395', applyZero($value->current_arus_mudik_total_pelabuhan_sum));
            $sheet->setCellValue($arraylabel[$key].'396', applyZero($value->current_arus_mudik_pelabuhan_kendaraan_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'397', applyZero($value->current_arus_mudik_pelabuhan_kendaraan_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'398', applyZero($value->current_arus_mudik_pelabuhan_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'399', applyZero($value->current_arus_mudik_pelabuhan_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'401', applyZero($value->current_arus_mudik_bandara_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'402', applyZero($value->current_arus_mudik_bandara_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'403', applyZero($value->current_arus_mudik_total_bandara_sum));
            $sheet->setCellValue($arraylabel[$key].'404', applyZero($value->current_arus_mudik_bandara_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'405', applyZero($value->current_arus_mudik_bandara_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'408', applyZero($value->current_prokes_covid_teguran_gar_prokes_sum));
            $sheet->setCellValue($arraylabel[$key].'409', applyZero($value->current_prokes_covid_pembagian_masker_sum));
            $sheet->setCellValue($arraylabel[$key].'410', applyZero($value->current_prokes_covid_sosialisasi_tentang_prokes_sum));
            $sheet->setCellValue($arraylabel[$key].'411', applyZero($value->current_prokes_covid_giat_baksos_sum));

            // TAMBAHKAN DISINI KEBAWAH.....
        }

        if(is_null($dailyRekap)) {
            $sheet->setCellValue('AI415', indonesiaDate(date("Y-m-d")));
            $sheet->setCellValue('AI416', $rencanaOperasi->name." - ".date("Y"));
        } else {
            $sheet->setCellValue('AI415', ucfirst(strtolower($dailyRekap->kota)).", ".indonesiaDate(date("Y-m-d")));
            $sheet->setCellValue('AI416', $dailyRekap->jabatan." ".$rencanaOperasi->name." - ".date("Y"));
            $sheet->setCellValue('AI420', $dailyRekap->atasan);
            $sheet->setCellValue('AI421', $dailyRekap->pangkat_nrp);
        }

        $writer = new Xlsx($spreadsheet);
        $writer->save('php://output');
    }
}

if (! function_exists('lapoanPerpoldaPerhariHTML')) {
    function lapoanPerpoldaPerhariHTML($data, $rencanaOperasi, $startDate, $endDate, $dailyRekap=null) {
        $arraylabel = [
            'C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL'
        ];

        $now = now()->format("Y-m-d");

        $filename = "LAPORAN-PERPOLPA-PERHARI";

        $excelPath = public_path('template/excel');
        $excelTemplate = $excelPath."/laporan_perpolda_perhari_html.xlsx";

        $reader = IOFactory::createReader('Xlsx');
        $spreadsheet = $reader->load($excelTemplate);
        $sheet = $spreadsheet->getActiveSheet();

        $sheet->setCellValue('A5', 'REKAPITULASI LAPORAN PERPOLDA '.gedein($rencanaOperasi->name).' '.date('Y'));
        $sheet->setCellValue('A6', 'TANGGAL '.strtoupper(indonesiaDate($startDate)).' s.d. '.strtoupper(indonesiaDate($endDate)));

        foreach($data as $key=>$value) {
            $poldaName  = $value->polda_name;
            $poldaId    = $value->polda_id;

            $sheet->setCellValue($arraylabel[$key].'12', applyZero($value->current_pelanggaran_lalu_lintas_tilang_sum));
            $sheet->setCellValue($arraylabel[$key].'13', applyZero($value->current_pelanggaran_lalu_lintas_teguran_sum));
            $sheet->setCellValue($arraylabel[$key].'13', applyZero($value->current_pelanggaran_lalu_lintas_teguran_sum));
            $sheet->setCellValue($arraylabel[$key].'17', applyZero($value->current_pelanggaran_sepeda_motor_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'18', applyZero($value->current_pelanggaran_sepeda_motor_helm_sum));
            $sheet->setCellValue($arraylabel[$key].'19', applyZero($value->current_pelanggaran_sepeda_motor_bonceng_lebih_dari_satu_sum));
            $sheet->setCellValue($arraylabel[$key].'20', applyZero($value->current_pelanggaran_sepeda_motor_marka_menerus_menyalip_sum));
            $sheet->setCellValue($arraylabel[$key].'21', applyZero($value->current_pelanggaran_sepeda_motor_melawan_arus_sum));
            $sheet->setCellValue($arraylabel[$key].'22', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_lampu_lalin_sum));
            $sheet->setCellValue($arraylabel[$key].'23', applyZero($value->current_pelanggaran_sepeda_motor_mengemudikan_tidak_wajar_sum));
            $sheet->setCellValue($arraylabel[$key].'24', applyZero($value->current_pelanggaran_sepeda_motor_syarat_teknis_layak_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'25', applyZero($value->current_pelanggaran_sepeda_motor_tidak_nyala_lampu_siang_malam_sum));
            $sheet->setCellValue($arraylabel[$key].'26', applyZero($value->current_pelanggaran_sepeda_motor_berbelok_tanpa_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'27', applyZero($value->current_pelanggaran_sepeda_motor_berbalapan_di_jalan_raya_sum));
            $sheet->setCellValue($arraylabel[$key].'28', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_rambu_berhenti_dan_parkir_sum));
            $sheet->setCellValue($arraylabel[$key].'29', applyZero($value->current_pelanggaran_sepeda_motor_melanggar_marka_berhenti_sum));
            $sheet->setCellValue($arraylabel[$key].'30', applyZero($value->current_pelanggaran_sepeda_motor_tidak_patuh_perintah_petugas_sum));
            $sheet->setCellValue($arraylabel[$key].'31', applyZero($value->current_pelanggaran_sepeda_motor_surat_surat_sum));
            $sheet->setCellValue($arraylabel[$key].'32', applyZero($value->current_pelanggaran_sepeda_motor_kelengkapan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'33', applyZero($value->current_pelanggaran_sepeda_motor_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'36', applyZero($value->current_pelanggaran_mobil_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'37', applyZero($value->current_pelanggaran_mobil_safety_belt_sum));
            $sheet->setCellValue($arraylabel[$key].'38', applyZero($value->current_pelanggaran_mobil_muatan_overload_sum));
            $sheet->setCellValue($arraylabel[$key].'39', applyZero($value->current_pelanggaran_mobil_marka_menerus_menyalip_sum));
            $sheet->setCellValue($arraylabel[$key].'40', applyZero($value->current_pelanggaran_mobil_melawan_arus_sum));
            $sheet->setCellValue($arraylabel[$key].'41', applyZero($value->current_pelanggaran_mobil_melanggar_lampu_lalin_sum));
            $sheet->setCellValue($arraylabel[$key].'42', applyZero($value->current_pelanggaran_mobil_mengemudi_tidak_wajar_sum));
            $sheet->setCellValue($arraylabel[$key].'43', applyZero($value->current_pelanggaran_mobil_syarat_teknis_layak_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'44', applyZero($value->current_pelanggaran_mobil_tidak_nyala_lampu_malam_sum));
            $sheet->setCellValue($arraylabel[$key].'45', applyZero($value->current_pelanggaran_mobil_berbelok_tanpa_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'46', applyZero($value->current_pelanggaran_mobil_berbalapan_di_jalan_raya_sum));
            $sheet->setCellValue($arraylabel[$key].'47', applyZero($value->current_pelanggaran_mobil_melanggar_rambu_berhenti_dan_parkir_sum));
            $sheet->setCellValue($arraylabel[$key].'48', applyZero($value->current_pelanggaran_mobil_melanggar_marka_berhenti_sum));
            $sheet->setCellValue($arraylabel[$key].'49', applyZero($value->current_pelanggaran_mobil_tidak_patuh_perintah_petugas_sum));
            $sheet->setCellValue($arraylabel[$key].'50', applyZero($value->current_pelanggaran_mobil_surat_surat_sum));
            $sheet->setCellValue($arraylabel[$key].'51', applyZero($value->current_pelanggaran_mobil_kelengkapan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'52', applyZero($value->current_pelanggaran_mobil_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'55', applyZero($value->current_pelanggaran_pejalan_kaki_menyeberang_tidak_pada_tempat_sum));
            $sheet->setCellValue($arraylabel[$key].'58', applyZero($value->current_barang_bukti_yg_disita_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'59', applyZero($value->current_barang_bukti_yg_disita_stnk_sum));
            $sheet->setCellValue($arraylabel[$key].'60', applyZero($value->current_barang_bukti_yg_disita_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'63', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_sepeda_motor_sum));
            $sheet->setCellValue($arraylabel[$key].'64', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_penumpang_sum));
            $sheet->setCellValue($arraylabel[$key].'65', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_bus_sum));
            $sheet->setCellValue($arraylabel[$key].'66', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_mobil_barang_sum));
            $sheet->setCellValue($arraylabel[$key].'67', applyZero($value->current_kendaraan_yang_terlibat_pelanggaran_kendaraan_khusus_sum));
            $sheet->setCellValue($arraylabel[$key].'70', applyZero($value->current_profesi_pelaku_pelanggaran_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'71', applyZero($value->current_profesi_pelaku_pelanggaran_karyawan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'72', applyZero($value->current_profesi_pelaku_pelanggaran_pelajar_mahasiswa_sum));
            $sheet->setCellValue($arraylabel[$key].'73', applyZero($value->current_profesi_pelaku_pelanggaran_pengemudi_supir_sum));
            $sheet->setCellValue($arraylabel[$key].'74', applyZero($value->current_profesi_pelaku_pelanggaran_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'75', applyZero($value->current_profesi_pelaku_pelanggaran_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'76', applyZero($value->current_profesi_pelaku_pelanggaran_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'79', applyZero($value->current_usia_pelaku_pelanggaran_kurang_dari_15_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'80', applyZero($value->current_usia_pelaku_pelanggaran_16_20_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'81', applyZero($value->current_usia_pelaku_pelanggaran_21_25_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'82', applyZero($value->current_usia_pelaku_pelanggaran_26_30_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'83', applyZero($value->current_usia_pelaku_pelanggaran_31_35_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'84', applyZero($value->current_usia_pelaku_pelanggaran_36_40_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'85', applyZero($value->current_usia_pelaku_pelanggaran_41_45_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'86', applyZero($value->current_usia_pelaku_pelanggaran_46_50_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'87', applyZero($value->current_usia_pelaku_pelanggaran_51_55_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'88', applyZero($value->current_usia_pelaku_pelanggaran_56_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'89', applyZero($value->current_usia_pelaku_pelanggaran_diatas_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'92', applyZero($value->current_sim_pelaku_pelanggaran_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'93', applyZero($value->current_sim_pelaku_pelanggaran_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'94', applyZero($value->current_sim_pelaku_pelanggaran_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'95', applyZero($value->current_sim_pelaku_pelanggaran_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'96', applyZero($value->current_sim_pelaku_pelanggaran_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'97', applyZero($value->current_sim_pelaku_pelanggaran_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'98', applyZero($value->current_sim_pelaku_pelanggaran_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'99', applyZero($value->current_sim_pelaku_pelanggaran_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'100', applyZero($value->current_sim_pelaku_pelanggaran_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'101', applyZero($value->current_sim_pelaku_pelanggaran_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'105', applyZero($value->current_lokasi_pelanggaran_pemukiman_sum));
            $sheet->setCellValue($arraylabel[$key].'106', applyZero($value->current_lokasi_pelanggaran_perbelanjaan_sum));
            $sheet->setCellValue($arraylabel[$key].'107', applyZero($value->current_lokasi_pelanggaran_perkantoran_sum));
            $sheet->setCellValue($arraylabel[$key].'108', applyZero($value->current_lokasi_pelanggaran_wisata_sum));
            $sheet->setCellValue($arraylabel[$key].'109', applyZero($value->current_lokasi_pelanggaran_industri_sum));
            $sheet->setCellValue($arraylabel[$key].'112', applyZero($value->current_lokasi_pelanggaran_status_jalan_nasional_sum));
            $sheet->setCellValue($arraylabel[$key].'113', applyZero($value->current_lokasi_pelanggaran_status_jalan_propinsi_sum));
            $sheet->setCellValue($arraylabel[$key].'114', applyZero($value->current_lokasi_pelanggaran_status_jalan_kab_kota_sum));
            $sheet->setCellValue($arraylabel[$key].'115', applyZero($value->current_lokasi_pelanggaran_status_jalan_desa_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'118', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_arteri_sum));
            $sheet->setCellValue($arraylabel[$key].'119', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_kolektor_sum));
            $sheet->setCellValue($arraylabel[$key].'120', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_lokal_sum));
            $sheet->setCellValue($arraylabel[$key].'121', applyZero($value->current_lokasi_pelanggaran_fungsi_jalan_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'125', applyZero($value->current_kecelakaan_lalin_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'126', applyZero($value->current_kecelakaan_lalin_jumlah_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'127', applyZero($value->current_kecelakaan_lalin_jumlah_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'128', applyZero($value->current_kecelakaan_lalin_jumlah_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'129', applyZero($value->current_kecelakaan_lalin_jumlah_kerugian_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'131', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'132', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_stnk_sum));
            $sheet->setCellValue($arraylabel[$key].'133', applyZero($value->current_kecelakaan_barang_bukti_yg_disita_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'136', applyZero($value->current_profesi_korban_kecelakaan_lalin_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'137', applyZero($value->current_profesi_korban_kecelakaan_lalin_karwayan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'138', applyZero($value->current_profesi_korban_kecelakaan_lalin_pelajar_mahasiswa_sum));
            $sheet->setCellValue($arraylabel[$key].'139', applyZero($value->current_profesi_korban_kecelakaan_lalin_pengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'140', applyZero($value->current_profesi_korban_kecelakaan_lalin_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'141', applyZero($value->current_profesi_korban_kecelakaan_lalin_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'142', applyZero($value->current_profesi_korban_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'145', applyZero($value->current_usia_korban_kecelakaan_kurang_15_sum));
            $sheet->setCellValue($arraylabel[$key].'146', applyZero($value->current_usia_korban_kecelakaan_16_20_sum));
            $sheet->setCellValue($arraylabel[$key].'147', applyZero($value->current_usia_korban_kecelakaan_21_25_sum));
            $sheet->setCellValue($arraylabel[$key].'148', applyZero($value->current_usia_korban_kecelakaan_26_30_sum));
            $sheet->setCellValue($arraylabel[$key].'149', applyZero($value->current_usia_korban_kecelakaan_31_35_sum));
            $sheet->setCellValue($arraylabel[$key].'150', applyZero($value->current_usia_korban_kecelakaan_36_40_sum));
            $sheet->setCellValue($arraylabel[$key].'151', applyZero($value->current_usia_korban_kecelakaan_41_45_sum));
            $sheet->setCellValue($arraylabel[$key].'152', applyZero($value->current_usia_korban_kecelakaan_45_50_sum));
            $sheet->setCellValue($arraylabel[$key].'153', applyZero($value->current_usia_korban_kecelakaan_51_55_sum));
            $sheet->setCellValue($arraylabel[$key].'154', applyZero($value->current_usia_korban_kecelakaan_56_60_sum));
            $sheet->setCellValue($arraylabel[$key].'155', applyZero($value->current_usia_korban_kecelakaan_diatas_60_sum));
            $sheet->setCellValue($arraylabel[$key].'158', applyZero($value->current_sim_korban_kecelakaan_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'159', applyZero($value->current_sim_korban_kecelakaan_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'160', applyZero($value->current_sim_korban_kecelakaan_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'161', applyZero($value->current_sim_korban_kecelakaan_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'162', applyZero($value->current_sim_korban_kecelakaan_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'163', applyZero($value->current_sim_korban_kecelakaan_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'164', applyZero($value->current_sim_korban_kecelakaan_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'165', applyZero($value->current_sim_korban_kecelakaan_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'166', applyZero($value->current_sim_korban_kecelakaan_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'167', applyZero($value->current_sim_korban_kecelakaan_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'170', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_sepeda_motor_sum));
            $sheet->setCellValue($arraylabel[$key].'171', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_penumpang_sum));
            $sheet->setCellValue($arraylabel[$key].'172', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_bus_sum));
            $sheet->setCellValue($arraylabel[$key].'173', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_mobil_barang_sum));
            $sheet->setCellValue($arraylabel[$key].'174', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_kendaraan_khusus_sum));
            $sheet->setCellValue($arraylabel[$key].'175', applyZero($value->current_kendaraan_yg_terlibat_kecelakaan_kendaraan_tidak_bermotor_sum));
            $sheet->setCellValue($arraylabel[$key].'178', applyZero($value->current_jenis_kecelakaan_tunggal_ooc_sum));
            $sheet->setCellValue($arraylabel[$key].'179', applyZero($value->current_jenis_kecelakaan_depan_depan_sum));
            $sheet->setCellValue($arraylabel[$key].'180', applyZero($value->current_jenis_kecelakaan_depan_belakang_sum));
            $sheet->setCellValue($arraylabel[$key].'181', applyZero($value->current_jenis_kecelakaan_depan_samping_sum));
            $sheet->setCellValue($arraylabel[$key].'182', applyZero($value->current_jenis_kecelakaan_beruntun_sum));
            $sheet->setCellValue($arraylabel[$key].'183', applyZero($value->current_jenis_kecelakaan_pejalan_kaki_sum));
            $sheet->setCellValue($arraylabel[$key].'184', applyZero($value->current_jenis_kecelakaan_tabrak_lari_sum));
            $sheet->setCellValue($arraylabel[$key].'185', applyZero($value->current_jenis_kecelakaan_tabrak_hewan_sum));
            $sheet->setCellValue($arraylabel[$key].'186', applyZero($value->current_jenis_kecelakaan_samping_samping_sum));
            $sheet->setCellValue($arraylabel[$key].'187', applyZero($value->current_jenis_kecelakaan_lainnya_sum));
            $sheet->setCellValue($arraylabel[$key].'190', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_pns_sum));
            $sheet->setCellValue($arraylabel[$key].'191', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_karyawan_swasta_sum));
            $sheet->setCellValue($arraylabel[$key].'192', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_mahasiswa_pelajar_sum));
            $sheet->setCellValue($arraylabel[$key].'193', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_pengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'194', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_tni_sum));
            $sheet->setCellValue($arraylabel[$key].'195', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_polri_sum));
            $sheet->setCellValue($arraylabel[$key].'196', applyZero($value->current_profesi_pelaku_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'199', applyZero($value->current_usia_pelaku_kecelakaan_kurang_dari_15_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'200', applyZero($value->current_usia_pelaku_kecelakaan_16_20_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'201', applyZero($value->current_usia_pelaku_kecelakaan_21_25_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'202', applyZero($value->current_usia_pelaku_kecelakaan_26_30_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'203', applyZero($value->current_usia_pelaku_kecelakaan_31_35_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'204', applyZero($value->current_usia_pelaku_kecelakaan_36_40_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'205', applyZero($value->current_usia_pelaku_kecelakaan_41_45_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'206', applyZero($value->current_usia_pelaku_kecelakaan_46_50_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'207', applyZero($value->current_usia_pelaku_kecelakaan_51_55_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'208', applyZero($value->current_usia_pelaku_kecelakaan_56_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'209', applyZero($value->current_usia_pelaku_kecelakaan_diatas_60_tahun_sum));
            $sheet->setCellValue($arraylabel[$key].'212', applyZero($value->current_sim_pelaku_kecelakaan_sim_a_sum));
            $sheet->setCellValue($arraylabel[$key].'213', applyZero($value->current_sim_pelaku_kecelakaan_sim_a_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'214', applyZero($value->current_sim_pelaku_kecelakaan_sim_b1_sum));
            $sheet->setCellValue($arraylabel[$key].'215', applyZero($value->current_sim_pelaku_kecelakaan_sim_b1_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'216', applyZero($value->current_sim_pelaku_kecelakaan_sim_b2_sum));
            $sheet->setCellValue($arraylabel[$key].'217', applyZero($value->current_sim_pelaku_kecelakaan_sim_b2_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'218', applyZero($value->current_sim_pelaku_kecelakaan_sim_c_sum));
            $sheet->setCellValue($arraylabel[$key].'219', applyZero($value->current_sim_pelaku_kecelakaan_sim_d_sum));
            $sheet->setCellValue($arraylabel[$key].'220', applyZero($value->current_sim_pelaku_kecelakaan_sim_internasional_sum));
            $sheet->setCellValue($arraylabel[$key].'221', applyZero($value->current_sim_pelaku_kecelakaan_tanpa_sim_sum));
            $sheet->setCellValue($arraylabel[$key].'225', applyZero($value->current_lokasi_kecelakaan_lalin_pemukiman_sum));
            $sheet->setCellValue($arraylabel[$key].'226', applyZero($value->current_lokasi_kecelakaan_lalin_perbelanjaan_sum));
            $sheet->setCellValue($arraylabel[$key].'227', applyZero($value->current_lokasi_kecelakaan_lalin_perkantoran_sum));
            $sheet->setCellValue($arraylabel[$key].'228', applyZero($value->current_lokasi_kecelakaan_lalin_wisata_sum));
            $sheet->setCellValue($arraylabel[$key].'229', applyZero($value->current_lokasi_kecelakaan_lalin_industri_sum));
            $sheet->setCellValue($arraylabel[$key].'230', applyZero($value->current_lokasi_kecelakaan_lalin_lain_lain_sum));
            $sheet->setCellValue($arraylabel[$key].'233', applyZero($value->current_lokasi_kecelakaan_status_jalan_nasional_sum));
            $sheet->setCellValue($arraylabel[$key].'234', applyZero($value->current_lokasi_kecelakaan_status_jalan_propinsi_sum));
            $sheet->setCellValue($arraylabel[$key].'235', applyZero($value->current_lokasi_kecelakaan_status_jalan_kab_kota_sum));
            $sheet->setCellValue($arraylabel[$key].'236', applyZero($value->current_lokasi_kecelakaan_status_jalan_desa_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'239', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_arteri_sum));
            $sheet->setCellValue($arraylabel[$key].'240', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_kolektor_sum));
            $sheet->setCellValue($arraylabel[$key].'241', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_lokal_sum));
            $sheet->setCellValue($arraylabel[$key].'242', applyZero($value->current_lokasi_kecelakaan_fungsi_jalan_lingkungan_sum));
            $sheet->setCellValue($arraylabel[$key].'245', applyZero($value->current_faktor_penyebab_kecelakaan_manusia_sum));
            $sheet->setCellValue($arraylabel[$key].'246', applyZero($value->current_faktor_penyebab_kecelakaan_ngantuk_lelah_sum));
            $sheet->setCellValue($arraylabel[$key].'247', applyZero($value->current_faktor_penyebab_kecelakaan_mabuk_obat_sum));
            $sheet->setCellValue($arraylabel[$key].'248', applyZero($value->current_faktor_penyebab_kecelakaan_sakit_sum));
            $sheet->setCellValue($arraylabel[$key].'249', applyZero($value->current_faktor_penyebab_kecelakaan_handphone_elektronik_sum));
            $sheet->setCellValue($arraylabel[$key].'250', applyZero($value->current_faktor_penyebab_kecelakaan_menerobos_lampu_merah_sum));
            $sheet->setCellValue($arraylabel[$key].'251', applyZero($value->current_faktor_penyebab_kecelakaan_melanggar_batas_kecepatan_sum));
            $sheet->setCellValue($arraylabel[$key].'252', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_menjaga_jarak_sum));
            $sheet->setCellValue($arraylabel[$key].'253', applyZero($value->current_faktor_penyebab_kecelakaan_mendahului_berbelok_pindah_jalur_sum));
            $sheet->setCellValue($arraylabel[$key].'254', applyZero($value->current_faktor_penyebab_kecelakaan_berpindah_jalur_sum));
            $sheet->setCellValue($arraylabel[$key].'255', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_memberikan_lampu_isyarat_sum));
            $sheet->setCellValue($arraylabel[$key].'256', applyZero($value->current_faktor_penyebab_kecelakaan_tidak_mengutamakan_pejalan_kaki_sum));
            $sheet->setCellValue($arraylabel[$key].'257', applyZero($value->current_faktor_penyebab_kecelakaan_lainnya_sum));
            $sheet->setCellValue($arraylabel[$key].'258', applyZero($value->current_faktor_penyebab_kecelakaan_alam_sum));
            $sheet->setCellValue($arraylabel[$key].'259', applyZero($value->current_faktor_penyebab_kecelakaan_kelaikan_kendaraan_sum));
            $sheet->setCellValue($arraylabel[$key].'260', applyZero($value->current_faktor_penyebab_kecelakaan_kondisi_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'261', applyZero($value->current_faktor_penyebab_kecelakaan_prasarana_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'262', applyZero($value->current_faktor_penyebab_kecelakaan_prasarana_jalan_sum));
            $sheet->setCellValue($arraylabel[$key].'263', applyZero($value->current_faktor_penyebab_kecelakaan_marka_sum));
            $sheet->setCellValue($arraylabel[$key].'264', applyZero($value->current_faktor_penyebab_kecelakaan_apil_sum));
            $sheet->setCellValue($arraylabel[$key].'265', applyZero($value->current_faktor_penyebab_kecelakaan_perlintasan_ka_palang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'268', applyZero($value->current_waktu_kejadian_kecelakaan_00_03_sum));
            $sheet->setCellValue($arraylabel[$key].'269', applyZero($value->current_waktu_kejadian_kecelakaan_03_06_sum));
            $sheet->setCellValue($arraylabel[$key].'270', applyZero($value->current_waktu_kejadian_kecelakaan_06_09_sum));
            $sheet->setCellValue($arraylabel[$key].'271', applyZero($value->current_waktu_kejadian_kecelakaan_09_12_sum));
            $sheet->setCellValue($arraylabel[$key].'272', applyZero($value->current_waktu_kejadian_kecelakaan_12_15_sum));
            $sheet->setCellValue($arraylabel[$key].'273', applyZero($value->current_waktu_kejadian_kecelakaan_15_18_sum));
            $sheet->setCellValue($arraylabel[$key].'274', applyZero($value->current_waktu_kejadian_kecelakaan_18_21_sum));
            $sheet->setCellValue($arraylabel[$key].'275', applyZero($value->current_waktu_kejadian_kecelakaan_21_24_sum));
            $sheet->setCellValue($arraylabel[$key].'278', applyZero($value->current_kecelakaan_lalin_menonjol_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'279', applyZero($value->current_kecelakaan_lalin_menonjol_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'280', applyZero($value->current_kecelakaan_lalin_menonjol_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'281', applyZero($value->current_kecelakaan_lalin_menonjol_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'282', applyZero($value->current_kecelakaan_lalin_menonjol_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'284', applyZero($value->current_kecelakaan_lalin_tunggal_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'285', applyZero($value->current_kecelakaan_lalin_tunggal_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'286', applyZero($value->current_kecelakaan_lalin_tunggal_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'287', applyZero($value->current_kecelakaan_lalin_tunggal_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'288', applyZero($value->current_kecelakaan_lalin_tunggal_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'290', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'291', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'292', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'293', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'294', applyZero($value->current_kecelakaan_lalin_tabrak_pejalan_kaki_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'296', applyZero($value->current_kecelakaan_lalin_tabrak_lari_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'297', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'298', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'299', applyZero($value->current_kecelakaan_lalin_tabrak_lari_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'300', applyZero($value->current_kecelakaan_lalin_tabrak_lari_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'302', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'303', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'304', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'305', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'306', applyZero($value->current_kecelakaan_lalin_tabrak_sepeda_motor_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'308', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'309', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'310', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'311', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'312', applyZero($value->current_kecelakaan_lalin_tabrak_roda_empat_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'314', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'315', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'316', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'317', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'318', applyZero($value->current_kecelakaan_lalin_tabrak_tidak_bermotor_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'320', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_jumlah_kejadian_sum));
            $sheet->setCellValue($arraylabel[$key].'321', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_berpalang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'322', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_tidak_berpalang_pintu_sum));
            $sheet->setCellValue($arraylabel[$key].'323', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_luka_ringan_sum));
            $sheet->setCellValue($arraylabel[$key].'324', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_luka_berat_sum));
            $sheet->setCellValue($arraylabel[$key].'325', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_korban_meninggal_sum));
            $sheet->setCellValue($arraylabel[$key].'326', applyZero($value->current_kecelakaan_lalin_perlintasan_ka_materiil_sum));
            $sheet->setCellValue($arraylabel[$key].'328', applyZero($value->current_kecelakaan_transportasi_kereta_api_sum));
            $sheet->setCellValue($arraylabel[$key].'329', applyZero($value->current_kecelakaan_transportasi_laut_perairan_sum));
            $sheet->setCellValue($arraylabel[$key].'330', applyZero($value->current_kecelakaan_transportasi_udara_sum));
            $sheet->setCellValue($arraylabel[$key].'335', applyZero($value->current_penlu_melalui_media_cetak_sum));
            $sheet->setCellValue($arraylabel[$key].'336', applyZero($value->current_penlu_melalui_media_elektronik_sum));
            $sheet->setCellValue($arraylabel[$key].'337', applyZero($value->current_penlu_melalui_media_sosial_sum));
            $sheet->setCellValue($arraylabel[$key].'338', applyZero($value->current_penlu_melalui_tempat_keramaian_sum));
            $sheet->setCellValue($arraylabel[$key].'339', applyZero($value->current_penlu_melalui_tempat_istirahat_sum));
            $sheet->setCellValue($arraylabel[$key].'340', applyZero($value->current_penlu_melalui_daerah_rawan_laka_dan_langgar_sum));
            $sheet->setCellValue($arraylabel[$key].'343', applyZero($value->current_penyebaran_pemasangan_spanduk_sum));
            $sheet->setCellValue($arraylabel[$key].'344', applyZero($value->current_penyebaran_pemasangan_leaflet_sum));
            $sheet->setCellValue($arraylabel[$key].'345', applyZero($value->current_penyebaran_pemasangan_sticker_sum));
            $sheet->setCellValue($arraylabel[$key].'346', applyZero($value->current_penyebaran_pemasangan_bilboard_sum));
            $sheet->setCellValue($arraylabel[$key].'349', applyZero($value->current_polisi_sahabat_anak_sum));
            $sheet->setCellValue($arraylabel[$key].'350', applyZero($value->current_cara_aman_sekolah_sum));
            $sheet->setCellValue($arraylabel[$key].'351', applyZero($value->current_patroli_keamanan_sekolah_sum));
            $sheet->setCellValue($arraylabel[$key].'352', applyZero($value->current_pramuka_bhayangkara_krida_lalu_lintas_sum));
            $sheet->setCellValue($arraylabel[$key].'355', applyZero($value->current_police_goes_to_campus_sum));
            $sheet->setCellValue($arraylabel[$key].'356', applyZero($value->current_safety_riding_driving_sum));
            $sheet->setCellValue($arraylabel[$key].'357', applyZero($value->current_forum_lalu_lintas_angkutan_umum_sum));
            $sheet->setCellValue($arraylabel[$key].'358', applyZero($value->current_kampanye_keselamatan_sum));
            $sheet->setCellValue($arraylabel[$key].'359', applyZero($value->current_sekolah_mengemudi_sum));
            $sheet->setCellValue($arraylabel[$key].'360', applyZero($value->current_taman_lalu_lintas_sum));
            $sheet->setCellValue($arraylabel[$key].'361', applyZero($value->current_global_road_safety_partnership_action_sum));
            $sheet->setCellValue($arraylabel[$key].'365', applyZero($value->current_giat_lantas_pengaturan_sum));
            $sheet->setCellValue($arraylabel[$key].'366', applyZero($value->current_giat_lantas_penjagaan_sum));
            $sheet->setCellValue($arraylabel[$key].'367', applyZero($value->current_giat_lantas_pengawalan_sum));
            $sheet->setCellValue($arraylabel[$key].'368', applyZero($value->current_giat_lantas_patroli_sum));
            $sheet->setCellValue($arraylabel[$key].'373', applyZero($value->current_arus_mudik_jumlah_bus_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'374', applyZero($value->current_arus_mudik_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'375', applyZero($value->current_arus_mudik_jumlah_bus_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'376', applyZero($value->current_arus_mudik_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'377', applyZero($value->current_arus_mudik_total_terminal_sum));
            $sheet->setCellValue($arraylabel[$key].'378', applyZero($value->current_arus_mudik_total_bus_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'379', applyZero($value->current_arus_mudik_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'380', applyZero($value->current_arus_mudik_total_bus_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'381', applyZero($value->current_arus_mudik_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'383', applyZero($value->current_arus_mudik_kereta_api_total_stasiun_sum));
            $sheet->setCellValue($arraylabel[$key].'384', applyZero($value->current_arus_mudik_kereta_api_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'385', applyZero($value->current_arus_mudik_kereta_api_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'387', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'388', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r4_sum));
            $sheet->setCellValue($arraylabel[$key].'389', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r2_sum));
            $sheet->setCellValue($arraylabel[$key].'390', applyZero($value->current_arus_mudik_pelabuhan_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'391', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'392', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r4_sum));
            $sheet->setCellValue($arraylabel[$key].'393', applyZero($value->current_arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r2_sum));
            $sheet->setCellValue($arraylabel[$key].'394', applyZero($value->current_arus_mudik_pelabuhan_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'395', applyZero($value->current_arus_mudik_total_pelabuhan_sum));
            $sheet->setCellValue($arraylabel[$key].'396', applyZero($value->current_arus_mudik_pelabuhan_kendaraan_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'397', applyZero($value->current_arus_mudik_pelabuhan_kendaraan_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'398', applyZero($value->current_arus_mudik_pelabuhan_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'399', applyZero($value->current_arus_mudik_pelabuhan_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'401', applyZero($value->current_arus_mudik_bandara_jumlah_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'402', applyZero($value->current_arus_mudik_bandara_jumlah_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'403', applyZero($value->current_arus_mudik_total_bandara_sum));
            $sheet->setCellValue($arraylabel[$key].'404', applyZero($value->current_arus_mudik_bandara_total_penumpang_keberangkatan_sum));
            $sheet->setCellValue($arraylabel[$key].'405', applyZero($value->current_arus_mudik_bandara_total_penumpang_kedatangan_sum));
            $sheet->setCellValue($arraylabel[$key].'408', applyZero($value->current_prokes_covid_teguran_gar_prokes_sum));
            $sheet->setCellValue($arraylabel[$key].'409', applyZero($value->current_prokes_covid_pembagian_masker_sum));
            $sheet->setCellValue($arraylabel[$key].'410', applyZero($value->current_prokes_covid_sosialisasi_tentang_prokes_sum));
            $sheet->setCellValue($arraylabel[$key].'411', applyZero($value->current_prokes_covid_giat_baksos_sum));

            // TAMBAHKAN DISINI KEBAWAH.....
        }

        if(is_null($dailyRekap)) {
            $sheet->setCellValue('AI415', indonesiaDate(date("Y-m-d")));
            $sheet->setCellValue('AI416', $rencanaOperasi->name." - ".date("Y"));
        } else {
            $sheet->setCellValue('AI415', ucfirst(strtolower($dailyRekap->kota)).", ".indonesiaDate(date("Y-m-d")));
            $sheet->setCellValue('AI416', $dailyRekap->jabatan." ".$rencanaOperasi->name." - ".date("Y"));
            $sheet->setCellValue('AI420', $dailyRekap->atasan);
            $sheet->setCellValue('AI421', $dailyRekap->pangkat_nrp);
        }

        $writer = IOFactory::createWriter($spreadsheet, 'Html');
        $message = $writer->save('php://output');

        return $message;
    }
}

if (! function_exists('sumByPoldaId')) {
    function sumByPoldaId($operationId, $current_year, $start_date, $end_date, $poldaId) {
        return SortablePoldaReport::withSum(['bypoldaid:pelanggaran_lalu_lintas_tilang,pelanggaran_lalu_lintas_teguran,pelanggaran_sepeda_motor_kecepatan,pelanggaran_sepeda_motor_helm,pelanggaran_sepeda_motor_bonceng_lebih_dari_satu,pelanggaran_sepeda_motor_marka_menerus_menyalip,pelanggaran_sepeda_motor_melawan_arus,pelanggaran_sepeda_motor_melanggar_lampu_lalin,pelanggaran_sepeda_motor_mengemudikan_tidak_wajar,pelanggaran_sepeda_motor_syarat_teknis_layak_jalan,pelanggaran_sepeda_motor_tidak_nyala_lampu_siang_malam,pelanggaran_sepeda_motor_berbelok_tanpa_isyarat,pelanggaran_sepeda_motor_berbalapan_di_jalan_raya,pelanggaran_sepeda_motor_melanggar_rambu_berhenti_dan_parkir,pelanggaran_sepeda_motor_melanggar_marka_berhenti,pelanggaran_sepeda_motor_tidak_patuh_perintah_petugas,pelanggaran_sepeda_motor_surat_surat,pelanggaran_sepeda_motor_kelengkapan_kendaraan,pelanggaran_sepeda_motor_lain_lain,pelanggaran_mobil_kecepatan,pelanggaran_mobil_safety_belt,pelanggaran_mobil_muatan_overload,pelanggaran_mobil_marka_menerus_menyalip,pelanggaran_mobil_melawan_arus,pelanggaran_mobil_melanggar_lampu_lalin,pelanggaran_mobil_mengemudi_tidak_wajar,pelanggaran_mobil_syarat_teknis_layak_jalan,pelanggaran_mobil_tidak_nyala_lampu_malam,pelanggaran_mobil_berbelok_tanpa_isyarat,pelanggaran_mobil_berbalapan_di_jalan_raya,pelanggaran_mobil_melanggar_rambu_berhenti_dan_parkir,pelanggaran_mobil_melanggar_marka_berhenti,pelanggaran_mobil_tidak_patuh_perintah_petugas,pelanggaran_mobil_surat_surat,pelanggaran_mobil_kelengkapan_kendaraan,pelanggaran_mobil_lain_lain,pelanggaran_pejalan_kaki_menyeberang_tidak_pada_tempat,barang_bukti_yg_disita_sim,barang_bukti_yg_disita_stnk,barang_bukti_yg_disita_kendaraan,kendaraan_yang_terlibat_pelanggaran_sepeda_motor,kendaraan_yang_terlibat_pelanggaran_mobil_penumpang,kendaraan_yang_terlibat_pelanggaran_mobil_bus,kendaraan_yang_terlibat_pelanggaran_mobil_barang,kendaraan_yang_terlibat_pelanggaran_kendaraan_khusus,profesi_pelaku_pelanggaran_pns,profesi_pelaku_pelanggaran_karyawan_swasta,profesi_pelaku_pelanggaran_pelajar_mahasiswa,profesi_pelaku_pelanggaran_pengemudi_supir,profesi_pelaku_pelanggaran_tni,profesi_pelaku_pelanggaran_polri,profesi_pelaku_pelanggaran_lain_lain,usia_pelaku_pelanggaran_kurang_dari_15_tahun,usia_pelaku_pelanggaran_16_20_tahun,usia_pelaku_pelanggaran_21_25_tahun,usia_pelaku_pelanggaran_26_30_tahun,usia_pelaku_pelanggaran_31_35_tahun,usia_pelaku_pelanggaran_36_40_tahun,usia_pelaku_pelanggaran_41_45_tahun,usia_pelaku_pelanggaran_46_50_tahun,usia_pelaku_pelanggaran_51_55_tahun,usia_pelaku_pelanggaran_56_60_tahun,usia_pelaku_pelanggaran_diatas_60_tahun,sim_pelaku_pelanggaran_sim_a,sim_pelaku_pelanggaran_sim_a_umum,sim_pelaku_pelanggaran_sim_b1,sim_pelaku_pelanggaran_sim_b1_umum,sim_pelaku_pelanggaran_sim_b2,sim_pelaku_pelanggaran_sim_b2_umum,sim_pelaku_pelanggaran_sim_c,sim_pelaku_pelanggaran_sim_d,sim_pelaku_pelanggaran_sim_internasional,sim_pelaku_pelanggaran_tanpa_sim,lokasi_pelanggaran_pemukiman,lokasi_pelanggaran_perbelanjaan,lokasi_pelanggaran_perkantoran,lokasi_pelanggaran_wisata,lokasi_pelanggaran_industri,lokasi_pelanggaran_status_jalan_nasional,lokasi_pelanggaran_status_jalan_propinsi,lokasi_pelanggaran_status_jalan_kab_kota,lokasi_pelanggaran_status_jalan_desa_lingkungan,lokasi_pelanggaran_fungsi_jalan_arteri,lokasi_pelanggaran_fungsi_jalan_kolektor,lokasi_pelanggaran_fungsi_jalan_lokal,lokasi_pelanggaran_fungsi_jalan_lingkungan,kecelakaan_lalin_jumlah_kejadian,kecelakaan_lalin_jumlah_korban_meninggal,kecelakaan_lalin_jumlah_korban_luka_berat,kecelakaan_lalin_jumlah_korban_luka_ringan,kecelakaan_lalin_jumlah_kerugian_materiil,kecelakaan_barang_bukti_yg_disita_sim,kecelakaan_barang_bukti_yg_disita_stnk,kecelakaan_barang_bukti_yg_disita_kendaraan,profesi_korban_kecelakaan_lalin_pns,profesi_korban_kecelakaan_lalin_karwayan_swasta,profesi_korban_kecelakaan_lalin_pelajar_mahasiswa,profesi_korban_kecelakaan_lalin_pengemudi,profesi_korban_kecelakaan_lalin_tni,profesi_korban_kecelakaan_lalin_polri,profesi_korban_kecelakaan_lalin_lain_lain,usia_korban_kecelakaan_kurang_15,usia_korban_kecelakaan_16_20,usia_korban_kecelakaan_21_25,usia_korban_kecelakaan_26_30,usia_korban_kecelakaan_31_35,usia_korban_kecelakaan_36_40,usia_korban_kecelakaan_41_45,usia_korban_kecelakaan_45_50,usia_korban_kecelakaan_51_55,usia_korban_kecelakaan_56_60,usia_korban_kecelakaan_diatas_60,sim_korban_kecelakaan_sim_a,sim_korban_kecelakaan_sim_a_umum,sim_korban_kecelakaan_sim_b1,sim_korban_kecelakaan_sim_b1_umum,sim_korban_kecelakaan_sim_b2,sim_korban_kecelakaan_sim_b2_umum,sim_korban_kecelakaan_sim_c,sim_korban_kecelakaan_sim_d,sim_korban_kecelakaan_sim_internasional,sim_korban_kecelakaan_tanpa_sim,kendaraan_yg_terlibat_kecelakaan_sepeda_motor,kendaraan_yg_terlibat_kecelakaan_mobil_penumpang,kendaraan_yg_terlibat_kecelakaan_mobil_bus,kendaraan_yg_terlibat_kecelakaan_mobil_barang,kendaraan_yg_terlibat_kecelakaan_kendaraan_khusus,kendaraan_yg_terlibat_kecelakaan_kendaraan_tidak_bermotor,jenis_kecelakaan_tunggal_ooc,jenis_kecelakaan_depan_depan,jenis_kecelakaan_depan_belakang,jenis_kecelakaan_depan_samping,jenis_kecelakaan_beruntun,jenis_kecelakaan_pejalan_kaki,jenis_kecelakaan_tabrak_lari,jenis_kecelakaan_tabrak_hewan,jenis_kecelakaan_samping_samping,jenis_kecelakaan_lainnya,profesi_pelaku_kecelakaan_lalin_pns,profesi_pelaku_kecelakaan_lalin_karyawan_swasta,profesi_pelaku_kecelakaan_lalin_mahasiswa_pelajar,profesi_pelaku_kecelakaan_lalin_pengemudi,profesi_pelaku_kecelakaan_lalin_tni,profesi_pelaku_kecelakaan_lalin_polri,profesi_pelaku_kecelakaan_lalin_lain_lain,usia_pelaku_kecelakaan_kurang_dari_15_tahun,usia_pelaku_kecelakaan_16_20_tahun,usia_pelaku_kecelakaan_21_25_tahun,usia_pelaku_kecelakaan_26_30_tahun,usia_pelaku_kecelakaan_31_35_tahun,usia_pelaku_kecelakaan_36_40_tahun,usia_pelaku_kecelakaan_41_45_tahun,usia_pelaku_kecelakaan_46_50_tahun,usia_pelaku_kecelakaan_51_55_tahun,usia_pelaku_kecelakaan_56_60_tahun,usia_pelaku_kecelakaan_diatas_60_tahun,sim_pelaku_kecelakaan_sim_a,sim_pelaku_kecelakaan_sim_a_umum,sim_pelaku_kecelakaan_sim_b1,sim_pelaku_kecelakaan_sim_b1_umum,sim_pelaku_kecelakaan_sim_b2,sim_pelaku_kecelakaan_sim_b2_umum,sim_pelaku_kecelakaan_sim_c,sim_pelaku_kecelakaan_sim_d,sim_pelaku_kecelakaan_sim_internasional,sim_pelaku_kecelakaan_tanpa_sim,lokasi_kecelakaan_lalin_pemukiman,lokasi_kecelakaan_lalin_perbelanjaan,lokasi_kecelakaan_lalin_perkantoran,lokasi_kecelakaan_lalin_wisata,lokasi_kecelakaan_lalin_industri,lokasi_kecelakaan_lalin_lain_lain,lokasi_kecelakaan_status_jalan_nasional,lokasi_kecelakaan_status_jalan_propinsi,lokasi_kecelakaan_status_jalan_kab_kota,lokasi_kecelakaan_status_jalan_desa_lingkungan,lokasi_kecelakaan_fungsi_jalan_arteri,lokasi_kecelakaan_fungsi_jalan_kolektor,lokasi_kecelakaan_fungsi_jalan_lokal,lokasi_kecelakaan_fungsi_jalan_lingkungan,faktor_penyebab_kecelakaan_manusia,faktor_penyebab_kecelakaan_ngantuk_lelah,faktor_penyebab_kecelakaan_mabuk_obat,faktor_penyebab_kecelakaan_sakit,faktor_penyebab_kecelakaan_handphone_elektronik,faktor_penyebab_kecelakaan_menerobos_lampu_merah,faktor_penyebab_kecelakaan_melanggar_batas_kecepatan,faktor_penyebab_kecelakaan_tidak_menjaga_jarak,faktor_penyebab_kecelakaan_mendahului_berbelok_pindah_jalur,faktor_penyebab_kecelakaan_berpindah_jalur,faktor_penyebab_kecelakaan_tidak_memberikan_lampu_isyarat,faktor_penyebab_kecelakaan_tidak_mengutamakan_pejalan_kaki,faktor_penyebab_kecelakaan_lainnya,faktor_penyebab_kecelakaan_alam,faktor_penyebab_kecelakaan_kelaikan_kendaraan,faktor_penyebab_kecelakaan_kondisi_jalan,faktor_penyebab_kecelakaan_prasarana_jalan,faktor_penyebab_kecelakaan_rambu,faktor_penyebab_kecelakaan_marka,faktor_penyebab_kecelakaan_apil,faktor_penyebab_kecelakaan_perlintasan_ka_palang_pintu,waktu_kejadian_kecelakaan_00_03,waktu_kejadian_kecelakaan_03_06,waktu_kejadian_kecelakaan_06_09,waktu_kejadian_kecelakaan_09_12,waktu_kejadian_kecelakaan_12_15,waktu_kejadian_kecelakaan_15_18,waktu_kejadian_kecelakaan_18_21,waktu_kejadian_kecelakaan_21_24,kecelakaan_lalin_menonjol_jumlah_kejadian,kecelakaan_lalin_menonjol_korban_meninggal,kecelakaan_lalin_menonjol_korban_luka_berat,kecelakaan_lalin_menonjol_korban_luka_ringan,kecelakaan_lalin_menonjol_materiil,kecelakaan_lalin_tunggal_jumlah_kejadian,kecelakaan_lalin_tunggal_korban_meninggal,kecelakaan_lalin_tunggal_korban_luka_berat,kecelakaan_lalin_tunggal_korban_luka_ringan,kecelakaan_lalin_tunggal_materiil,kecelakaan_lalin_tabrak_pejalan_kaki_jumlah_kejadian,kecelakaan_lalin_tabrak_pejalan_kaki_korban_meninggal,kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_berat,kecelakaan_lalin_tabrak_pejalan_kaki_korban_luka_ringan,kecelakaan_lalin_tabrak_pejalan_kaki_materiil,kecelakaan_lalin_tabrak_lari_jumlah_kejadian,kecelakaan_lalin_tabrak_lari_korban_meninggal,kecelakaan_lalin_tabrak_lari_korban_luka_berat,kecelakaan_lalin_tabrak_lari_korban_luka_ringan,kecelakaan_lalin_tabrak_lari_materiil,kecelakaan_lalin_tabrak_sepeda_motor_jumlah_kejadian,kecelakaan_lalin_tabrak_sepeda_motor_korban_meninggal,kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_berat,kecelakaan_lalin_tabrak_sepeda_motor_korban_luka_ringan,kecelakaan_lalin_tabrak_sepeda_motor_materiil,kecelakaan_lalin_tabrak_roda_empat_jumlah_kejadian,kecelakaan_lalin_tabrak_roda_empat_korban_meninggal,kecelakaan_lalin_tabrak_roda_empat_korban_luka_berat,kecelakaan_lalin_tabrak_roda_empat_korban_luka_ringan,kecelakaan_lalin_tabrak_roda_empat_materiil,kecelakaan_lalin_tabrak_tidak_bermotor_jumlah_kejadian,kecelakaan_lalin_tabrak_tidak_bermotor_korban_meninggal,kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_berat,kecelakaan_lalin_tabrak_tidak_bermotor_korban_luka_ringan,kecelakaan_lalin_tabrak_tidak_bermotor_materiil,kecelakaan_lalin_perlintasan_ka_jumlah_kejadian,kecelakaan_lalin_perlintasan_ka_berpalang_pintu,kecelakaan_lalin_perlintasan_ka_tidak_berpalang_pintu,kecelakaan_lalin_perlintasan_ka_korban_luka_ringan,kecelakaan_lalin_perlintasan_ka_korban_luka_berat,kecelakaan_lalin_perlintasan_ka_korban_meninggal,kecelakaan_lalin_perlintasan_ka_materiil,kecelakaan_transportasi_kereta_api,kecelakaan_transportasi_laut_perairan,kecelakaan_transportasi_udara,penlu_melalui_media_cetak,penlu_melalui_media_elektronik,penlu_melalui_media_sosial,penlu_melalui_tempat_keramaian,penlu_melalui_tempat_istirahat,penlu_melalui_daerah_rawan_laka_dan_langgar,penyebaran_pemasangan_spanduk,penyebaran_pemasangan_leaflet,penyebaran_pemasangan_sticker,penyebaran_pemasangan_bilboard,polisi_sahabat_anak,cara_aman_sekolah,patroli_keamanan_sekolah,pramuka_bhayangkara_krida_lalu_lintas,police_goes_to_campus,safety_riding_driving,forum_lalu_lintas_angkutan_umum,kampanye_keselamatan,sekolah_mengemudi,taman_lalu_lintas,global_road_safety_partnership_action,giat_lantas_pengaturan,giat_lantas_penjagaan,giat_lantas_pengawalan,giat_lantas_patroli,arus_mudik_jumlah_bus_keberangkatan,arus_mudik_jumlah_penumpang_keberangkatan,arus_mudik_jumlah_bus_kedatangan,arus_mudik_jumlah_penumpang_kedatangan,arus_mudik_total_terminal,arus_mudik_total_bus_keberangkatan,arus_mudik_penumpang_keberangkatan,arus_mudik_total_bus_kedatangan,arus_mudik_penumpang_kedatangan,arus_mudik_kereta_api_total_stasiun,arus_mudik_kereta_api_total_penumpang_keberangkatan,arus_mudik_kereta_api_total_penumpang_kedatangan,arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan,arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r4,arus_mudik_pelabuhan_jumlah_kendaraan_keberangkatan_r2,arus_mudik_pelabuhan_jumlah_penumpang_keberangkatan,arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan,arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r4,arus_mudik_pelabuhan_jumlah_kendaraan_kedatangan_r2,arus_mudik_pelabuhan_jumlah_penumpang_kedatangan,arus_mudik_total_pelabuhan,arus_mudik_pelabuhan_kendaraan_keberangkatan,arus_mudik_pelabuhan_kendaraan_kedatangan,arus_mudik_pelabuhan_total_penumpang_keberangkatan,arus_mudik_pelabuhan_total_penumpang_kedatangan,arus_mudik_bandara_jumlah_penumpang_keberangkatan,arus_mudik_bandara_jumlah_penumpang_kedatangan,arus_mudik_total_bandara,arus_mudik_bandara_total_penumpang_keberangkatan,arus_mudik_bandara_total_penumpang_kedatangan,prokes_covid_teguran_gar_prokes,prokes_covid_pembagian_masker,prokes_covid_sosialisasi_tentang_prokes,prokes_covid_giat_baksos,penyekatan_motor,penyekatan_mobil_penumpang,penyekatan_mobil_bus,penyekatan_mobil_barang,penyekatan_kendaraan_khusus,rapid_test_antigen_positif,rapid_test_antigen_negatif' => function (Builder $query) use ($operationId, $current_year, $start_date, $end_date) {
            $query->where('rencana_operasi_id', $operationId)
            ->where('year', $current_year)
            ->whereRaw("DATE(created_at) >= ? and DATE(created_at) <= ?", [$start_date, $end_date]);
        }])->where('polda_id', $poldaId)->first();

    }
}